export const commandTelemetryEmulator = [
  {
    id: 1,
    command: "THRUSTER_1021_TC_EXOTRAIL_GET_SYS_INFO",
    telemetry: "THRUSTER_1021_TM_EXOTRAIL_GET_SYS_INFO",
    target: "EMULATOR",
    parameters: [
      "SOFTWARE_VERSION",
      "EXOTRIAL_OBC_CURRENT_MODE",
      "ID_SAFE",
      "COMMISSIONING_RESULT",
    ],
    commandParams: [],
  },
  {
    id: 2,
    command: "THRUSTER_1022_TC_EXOTRAIL_GET_HEAT_ACTIVITY",
    telemetry: "THRUSTER_1022_TM_EXOTRAIL_GET_HEAT_ACTIVITY",
    target: "EMULATOR",
    parameters: ["THRUSTER_HEATER_ACTIVITY"],
    commandParams: [],
  },
  {
    id: 3,
    command: "THRUSTER_1023_TC_EXOTRAIL_GET_HK_FLUIDIC_INFO",
    telemetry: "THRUSTER_1023_TM_EXOTRAIL_GET_HK_FLUIDIC_INFO",
    target: "EMULATOR",
    parameters: ["ANODE_PULSE_COUNT", "CATHODE_PULSE_COUNT", "TANK_PRESSURE"],
    commandParams: [],
  },
  {
    id: 4,
    command: "THRUSTER_1024_TC_EXOTRAIL_GET_HK_FLUIDIC_INFO",
    telemetry: "THRUSTER_1024_TM_EXOTRAIL_GET_HK_FLUIDIC_INFO",
    target: "EMULATOR",
    parameters: [
      "PPU_OUTPUT_TEMPERATURE",
      "PPU_INPUT_VOLTAGE",
      "PPU_INPUT_CURRENT",
      "PPU_INPUT_TEMPERATURE",
    ],
    commandParams: [],
  },
  {
    id: 5,
    command: "THRUSTER_1025_TC_EXOTRAIL_GET_HK_THERMIC_INFO",
    telemetry: "THRUSTER_1025_TM_EXOTRAIL_GET_HK_THERMIC_INFO",
    target: "EMULATOR",
    parameters: [
      "TEMPERATURE_OF_THD_SUPPORT_1",
      "TEMPERATURE_OF_THD_RADIATOR_1",
      "TEMPERATURE_OF_THD_RADIATOR_2",
      "TEMPERATURE_OF_TCU_OBC_1",
      "TEMPERATURE_OF_PMS_ANODE_1",
      "TEMPERATURE_OF_PMS_ANODE_2",
      "TEMPERATURE_OF_PMS_CATHODE_1",
      "TEMPERATURE_OF_PMS_CATHODE_2",
      "TEMPERATURE_OF_PMS_INTERFACE_2",
    ],
    commandParams: [],
  },
  {
    id: 6,
    command: "OBC_581_TC_GET_CUR_TIME",
    telemetry: "OBC_581_TM_GET_CUR_TIME",
    target: "EMULATOR",
    parameters: [
      "Status",
      "Year",
      "Month",
      "Date",
      "Hours",
      "Minute",
      "Milliseconds",
    ],
    commandParams: [],
  },
  {
    id: 7,
    command: "THRUSTER_1026_TC_EXOTRAIL_GET_HK_POWER_INFO",
    telemetry: "THRUSTER_1026_TM_EXOTRAIL_GET_HK_POWER_INFO",
    target: "EMULATOR",
    parameters: [
      "Thruster_input_voltage_15v",
      "Thruster_2v5_ref_volt",
      "Thruster_input_volt_5v",
      "Thruster_input_volt_3v3",
    ],
    commandParams: [],
  },
  {
    id: 8,
    command: "THRUSTER_1027_TC_EXOTRAIL_GET_SAFE_LIMIT",
    telemetry: "THRUSTER_1027_TM_EXOTRAIL_GET_HK_FLUIDIC_INFO",
    target: "EMULATOR",
    parameters: [
      "Maximum_temperature_limit_for_Thruster_Head_Radiator_1",
      "Minimum_temperature_limit_for_Thruster_Head_Radiator_1",
      "Maximum_temperature_limit_for_Thruster_PMS_Anode_1",
      "Minimum_temperature_limit_for_Thruster_PMS_Anode_1",
      "Maximum_temperature_limit_for_Thruster_PMS_Cathode_1",
      "Minimum_temperature_limit_for_Thruster_PMS_Cathode_1",
      "Maximum_temperature_limit_for_Thruster_Head_Radiator_2",
      "Minimum_temperature_limit_for_Thruster_Head_Radiator_2",
      "Maximum_temperature_limit_for_Thruster_PMS_Anode_2",
      "Minimum_temperature_limit_for_Thruster_PMS_Anode_2",
      "Maximum_temperature_limit_for_Thruster_PMS_Cathode_2",
      "Minimum_temperature_limit_for_Thruster_PMS_Cathode_2",
      "Maximum_temperature_limit_for_Thruster_PMS_Pressure_1",
      "Minimum_temperature_limit_for_Thruster_PMS_Pressure_1",
      "Maximum_temperature_limit_for_Thruster_Thruster_Head_Supply_1",
      "Minimum_temperature_limit_for_Thruster_Head_Supply_1",
      "Maximum_temperature_limit_for_Thruster_TCU_OnBoard_Computer_1",
      "Minimum_temperature_limit_for_Thruster_TCU_OnBoard_Computer_1",
      "Maximum_temperature_for_PPU",
      "Maximum_pressure_for_tank",
    ],
    commandParams: [],
  },
  {
    id: 9,
    command: "THRUSTER_1028_TC_EXOTRAIL_GET_FLUIDIC_VALVE_SEL",
    telemetry: "THRUSTER_1028_TM_EXOTRAIL_GET_FLUIDIC_VALVE_SEL",
    target: "EMULATOR",
    parameters: ["FLUIDIC_VALVE_MODE"],
    commandParams: [],
  },
  {
    id: 10,
    command: "THRUSTER_1029_TC_EXOTRAIL_GET_HEATER_CFG",
    telemetry: "THRUSTER_1029_TM_EXOTRAIL_GET_HEATER_CFG",
    target: "EMULATOR",
    parameters: [
      "RADIATOR_LOW_TEMPERATURE",
      "RADIATOR_HIGH_TEMPERATURE",
      "RADIATOR_HEATING_DURATIONS_IN_MINUTES",
    ],
    commandParams: [],
  },
  {
    id: 11,
    command: "THRUSTER_1030_TC_EXOTRAIL_SET_FIRING_OPERATING_POINT",
    telemetry: "THRUSTER_1030_TM_EXOTRAIL_SET_FIRING_OPERATING_POINT",
    target: "EMULATOR",
    parameters: ["EXOTRAIL_MODE"],
    commandParams: ["FIRING_OPERATING_POINT"],
  },
  {
    id: 12,
    command: "THRUSTER_1031_TC_EXOTRAIL_TEST_SET_OBC_MODE",
    telemetry: "THRUSTER_1031_TM_EXOTRAIL_TEST_SET_OBC_MODE",
    target: "EMULATOR",
    parameters: ["EXOTRIAL_OBC_MODE"],
    commandParams: ["EXOTRIAL_OBC_MODE"],
  },
  {
    id: 13,
    command: "THRUSTER_1033_TC_EXOTRAIL_SET_SAFE_LIMIT",
    telemetry: "THRUSTER_1033_TM_EXOTRAIL_SET_SAFE_LIMIT",
    target: "EMULATOR",
    parameters: ["EXOTRAIL_MODE"],
    commandParams: [
      "MAXIMUM_TEMPERATURE_LIMIT_FOR_THRUSTER_HEAD_RADIATOR_1",
      "MINIMUM_TEMPERATURE_LIMIT_FOR_THRUSTER_HEAD_RADIATOR_1",
      "MAXIMUM_TEMPERATURE_LIMIT_FOR_THRUSTER_PMS_ANODE_1",
      "MINIMUM_TEMPERATURE_LIMIT_FOR_THRUSTER_PMS_ANODE_1",
      "MAXIMUM_TEMPERATURE_LIMIT_FOR_THRUSTER_PMS_CATHODE_1",
      "MINIMUM_TEMPERATURE_LIMIT_FOR_THRUSTER_PMS_CATHODE_1",
      "MAXIMUM_TEMPERATURE_LIMIT_FOR_THRUSTER_HEAD_RADIATOR_2",
      "MINIMUM_TEMPERATURE_LIMIT_FOR_THRUSTER_HEAD_RADIATOR_2",
      "MAXIMUM_TEMPERATURE_LIMIT_FOR_THRUSTER_PMS_ANODE_2",
      "MINIMUM_TEMPERATURE_LIMIT_FOR_THRUSTER_PMS_ANODE_2",
      "MAXIMUM_TEMPERATURE_LIMIT_FOR_THRUSTER_PMS_CATHODE_2",
      "MINIMUM_TEMPERATURE_LIMIT_FOR_THRUSTER_PMS_CATHODE_2",
      "MAXIMUM_TEMPERATURE_LIMIT_FOR_THRUSTER_PMS_PRESSURE_1",
      "MINIMUM_TEMPERATURE_LIMIT_FOR_THRUSTER_PMS_PRESSURE_1",
      "MAXIMUM_TEMPERATURE_LIMIT_FOR_THRUSTER_THRUSTER_HEAD_SUPPLY_1",
      "MINIMUM_TEMPERATURE_LIMIT_FOR_THRUSTER_HEAD_SUPPLY_1",
      "MAXIMUM_TEMPERATURE_LIMIT_FOR_THRUSTER_TCU_ONBOARD_COMPUTER_1",
      "MINIMUM_TEMPERATURE_LIMIT_FOR_THRUSTER_TCU_ONBOARD_COMPUTER_1",
      "MAXIMUM_TEMPERATURE_FOR_PPU",
      "MAXIMUM_PRESSURE_FOR_TANK",
    ],
  },
  {
    id: 14,
    command: "THRUSTER_1034_TC_EXOTRAIL_SET_FLUIDIC_VALVE_SEL",
    telemetry: "THRUSTER_1034_TM_EXOTRAIL_SET_FLUIDIC_VALVE_SEL",
    target: "EMULATOR",
    parameters: ["EXOTRAIL_MODE"],
    commandParams: ["FLUIDIC_VALVE_SELECTION"],
  },
  {
    id: 15,
    command: "THRUSTER_1036_TC_EXOTRAIL_SET_FIRING_DURATION",
    telemetry: "THRUSTER_1036_TM_EXOTRAIL_SET_FIRING_DURATION",
    target: "EMULATOR",
    parameters: ["EXOTRAIL_MODE"],
    commandParams: ["FIRING_DURATION_IN_MINUTES"],
  },
  {
    id: 16,
    command: "THRUSTER_1038_TC_OBC_EXOTRIAL_THRUSTER_TM_DECODE_DATA",
    telemetry: "THRUSTER_1038_TM_OBC_EXOTRIAL_THRUSTER_TM_DECODE_DATA",
    target: "EMULATOR",
    parameters: [
      "SOFTWARE_VERSION",
      "CURRENT_MODE_OF_OBC_IN_THRUSTER",
      "SAFETY_IDENTIFIER",
      "HEATER_ACTIVITY_STATUS",
      "PULSE_COUNT_FOR_ANODE_VALUE",
      "PULSE_COUNT_FOR_CATHODE_VALUE",
      "COMMISSIONING_RESULT",
      "PPU_OUTPUT_TEMP",
      "INPUT_VOLTAGE_MEASUREMENT",
      "INPUT_CURRENT_MEASUREMENT",
      "PPU_INPUT_TEMPERATURE",
      "TANK_PRESSURE",
      "TEMPERATURE_OF_THRUSTER_HEAD_SUPPORT_1",
      "TEMPERATURE_OF_THRUSTER_HEAD_RADIATOR_1",
      "TEMPERATURE_OF_THRUSTER_HEAD_RADIATOR_2",
      "TEMPERATURE_OF_TCU_ON_BOARD_CONTROLLER_1",
      "TEMPERATURE_OF_TANK_1_PMS_1",
      "TEMPERATURE_OF_TANK_2_PMS_1",
      "TEMPERATURE_OF_TANK_2_PMS_2",
      "TEMPERATURE_OF_TANK_2_PMS_3",
      "TEMPERATURE_OF_PMS_ANODE_1",
      "TEMPERATURE_OF_PMS_ANODE_2",
      "TEMPERATURE_OF_PMS_CATHODE_1",
      "TEMPERATURE_OF_PMS_CATHODE_2",
      "TEMPERATURE_OF_PMS_PRESSURE_1",
      "TEMPERATURE_OF_TANK_3_1_IN_PMS",
      "TEMPERATURE_OF_TANK_3_2_IN_PMS",
      "VOLTAGE_MEASUREMENT_AT_15V_INPUT",
      "POWER_15V_VALVES_2_AND_4",
      "REFERENCE_VOLTAGE_2V5",
      "VOLTAGE_MEASUREMENT_5V_INPUT",
      "VOLTAGE_MEASUREMENT_3V3_INPUT",
      "THRUSTER_OBC_MODE",
      "THERMAL_MEASUREMENT_FREQUENCY",
      "DURATION_OF_FIRING_EVENT",
      "LOWER_SETPOINT_RADIATOR_TEMP",
      "UPPER_SETPOINT_RADIATOR_TEMP",
      "RADIATOR_HEATING_DURATION",
      "LOWER_SETPOINT_TANK1",
      "UPPER_SETPOINT_TANK1",
      "TANK1_HEATING_DURATION",
      "LOWER_SETPOINT_TANK2",
      "UPPER_SETPOINT_TANK2",
      "TANK2_HEATING_DURATION",
      "LOWER_SETPOINT_TANK3",
      "UPPER_SETPOINT_TANK3",
      "TANK3_HEATING_DURATION",
      "FLUIDIC_VALVE_SELECTION",
      "MAX_THR_HEAD_RAD1_THERM_LIMIT",
      "MIN_THR_HEAD_RAD1_THERM_LIMIT",
      "MAX_PMS_ANODE1_THERM_LIMIT",
      "MIN_PMS_ANODE1_THERM_LIMIT",
      "MAX_PMS_CATHODE1_THERM_LIMIT",
      "MIN_PMS_CATHODE1_THERM_LIMIT",
      "MAX_THR_HEAD_RAD2_THERM_LIMIT",
      "MIN_THR_HEAD_RAD2_THERM_LIMIT",
      "MAX_PMS_ANODE2_THERM_LIMIT",
      "MIN_PMS_ANODE2_THERM_LIMIT",
      "MAX_PMS_CATHODE2_THERM_LIMIT",
      "MIN_PMS_CATHODE2_THERM_LIMIT",
      "MAX_PMS_PRESSURE1_THERM_LIMIT",
      "MIN_PMS_PRESSURE1_THERM_LIMIT",
      "MAX_THR_HEAD_SUPERVISION1_LIMIT",
      "MIN_THR_HEAD_SUPERVISION1_LIMIT",
      "MAX_TCU_OBC1_LIMIT",
      "MIN_TCU_OBC1_LIMIT",
      "MAX_PPU_TEMP_LIMIT",
      "MAX_TANK_PRESSURE",
      "MAGIC_NUMBER_1",
      "MAGIC_NUMBER_2",
      "STRUCTURE_END_FLAG_1",
      "STRUCTURE_END_FLAG_2",
    ],
    commandParams: [],
  },
  {
    id: 17,
    command: "OBC_500_TC_GET_PROC_UTIL_INFO",
    telemetry: "OBC_500_TM_GET_PROC_UTIL_INFO",
    target: "EMULATOR",
    parameters: ["CPU_USAGE"],
    commandParams: [],
  },
  {
    id: 18,
    command: "OBC_550_TC_SET_CUR_TIME",
    telemetry: "OBC_550_TM_SET_CUR_TIME",
    target: "EMULATOR",
    parameters: [
      "Year",
      "Month",
      "Date",
      "Hours",
      "Minute",
      "Milliseconds",
      "Status",
    ],
    commandParams: [
      "HOURS",
      "MINUTES",
      "MILLISECONDS",
      "DATE",
      "MONTH",
      "YEAR",
    ],
  },
  {
    id: 19,
    command: "FTM_SEND_DATA_PCKTS",
    telemetry: "",
    target: "EMULATOR",
    parameters: [],
    commandParams: [],
  },
  {
    id: 20,
    command: "TC_547",
    telemetry: "TM_547",
    target: "EMULATOR",
    parameters: ["SEGMENT_ID", "LUT_ID"],
    commandParams: ["EVENT"],
  },
  {
    id: 21,
    command: "TC_549",
    telemetry: "549_TM",
    target: "EMULATOR",
    parameters: [
      "Response_type",
      "UL_STATUS_1",
      "TOTAL_SEGMENTS_IN_LUT_1",
      "TOTAL_EVENTS_IN_LUT_1",
      "CURRENT_SEGMENT_ID",
      "CURRENT_EVENT_COUNT",
      "ID_OF_SEGMENTS_EXPECTED",
      "ID_OF_SEGMENTS_EXPECTED_7",
      "ID_OF_SEGMENTS_EXPECTED_6",
      "ID_OF_SEGMENTS_EXPECTED_5",
      "ID_OF_SEGMENTS_EXPECTED_4",
      "ID_OF_SEGMENTS_EXPECTED_3",
      "ID_OF_SEGMENTS_EXPECTED_2",
      "ID_OF_SEGMENTS_EXPECTED_1",
      "ID_OF_SEGMENTS_EXPECTED_0",
      "ID_OF_SEGMENTS_RECEIVED",
      "ID_OF_SEGMENTS_RECEIVED_7",
      "ID_OF_SEGMENTS_RECEIVED_6",
      "ID_OF_SEGMENTS_RECEIVED_5",
      "ID_OF_SEGMENTS_RECEIVED_4",
      "ID_OF_SEGMENTS_RECEIVED_3",
      "ID_OF_SEGMENTS_RECEIVED_2",
      "ID_OF_SEGMENTS_RECEIVED_1",
      "ID_OF_SEGMENTS_RECEIVED_0",
      "ID_OF_SEGMENTS_EXECUTED",
      "ID_OF_SEGMENTS_EXECUTED_7",
      "ID_OF_SEGMENTS_EXECUTED_6",
      "ID_OF_SEGMENTS_EXECUTED_5",
      "ID_OF_SEGMENTS_EXECUTED_4",
      "ID_OF_SEGMENTS_EXECUTED_3",
      "ID_OF_SEGMENTS_EXECUTED_2",
      "ID_OF_SEGMENTS_EXECUTED_1",
      "ID_OF_SEGMENTS_EXECUTED_0",
      "RESERVED_1",
    ],
    commandParams: ["STATUS"],
  },
  {
    id: 22,
    command: "TC_CONOPS_LUT_RUN_CTRL",
    telemetry: "TM_CONOPS_SCH_LUT_RUN_CTRL",
    target: "EMULATOR",
    parameters: ["STATUS"],
    commandParams: ["LUT_NUM", "ACTION"],
  },
  {
    id: 23,
    command: "TC_DEFFERED_STRG_OPT",
    telemetry: "TM_DEFERRED_STORAGE",
    target: "EMULATOR",
    parameters: ["ADDRESS_OFFSET"],
    commandParams: [],
  },
  {
    id: 24,
    command: "ADCS_129_TC_GET_ADCS_STATE_INFO",
    telemetry: "ADCS_129_TM_GET_ADCS_STATE_INFO",
    target: "EMULATOR",
    parameters: [
      "SOF3",
      "SOF4",
      "ID",
      "STATUS",
      "ATTITUDE_ESTIMATION_MODE",
      "CONTROL_MODE",
      "RESERVED",
      "EOF1",
      "EOF2",
    ],
    commandParams: ["SOF3", "SOF4", "ID", "EOF1", "EOF2"],
  },
  {
    id: 25,
    command: "ADCS_19_TC_3_AXIS_STABALISATION_MODE",
    telemetry: "ADCS_19_TM_SET_ADCS_CTRL_MODE_CONF",
    target: "EMULATOR",
    parameters: ["SOF3", "SOF4", "ID", "STATUS", "EOF1", "EOF2"],
    commandParams: [
      "SOF3",
      "SOF4",
      "ID",
      "STATUS",
      "EOF1",
      "EOF2",
      "CONTROL_MODE",
      "TIMEOUT_VALUE_FOR_ASSIGNED_CONTROL_MODE",
      "DEFAULT_CONTROL_MODE",
      "COMMANDED_ATTITUDE_QUATERNION_1",
      "COMMANDED_ATTITUDE_QUATERNION_2",
      "COMMANDED_ATTITUDE_QUATERNION_3",
      "COMMANDED_ATTITUDE_QUATERNION_4",
    ],
  },
  {
    id: 26,
    command: "ADCS_133_TC_GET_ADCS_MAG_FIELD_VEC",
    telemetry: "ADCS_133_TM_GET_ADCS_MAG_FIELD_VEC",
    target: "EMULATOR",
    parameters: [
      "SOF3",
      "SOF4",
      "ID",
      "STATUS",
      "X_AXIS_MAGNETIC_FIELD_VECTOR",
      "Y_AXIS_MAGNETIC_FIELD_VECTOR",
      "Z_AXIS_MAGNETIC_FIELD_VECTOR",
      "EOF1",
      "EOF2",
    ],
    commandParams: ["SOF3", "SOF4", "ID", "EOF1", "EOF2"],
  },
  {
    id: 27,
    command: "ADCS_117_TC_GET_ADCS_SAT_VEL_ECEF",
    telemetry: "ADCS_117_TM_GET_ADCS_SAT_VEL_ECEF",
    target: "EMULATOR",
    parameters: [
      "SOF3",
      "SOF4",
      "ID",
      "STATUS",
      "ECEF_REFERENCED_X_VELOCITY",
      "ECEF_REFERENCED_Y_VELOCITY",
      "ECEF_REFERENCED_Z_VELOCITY",
      "EOF1",
      "EOF2",
    ],
    commandParams: ["SOF3", "SOF4", "ID", "EOF1", "EOF2"],
  },
  {
    id: 28,
    command: "ADCS_134_TC_GET_ADCS_CSS_VEC",
    telemetry: "ADCS_134_TM_GET_ADCS_CSS_VEC",
    target: "EMULATOR",
    parameters: [
      "SOF3",
      "SOF4",
      "ID",
      "STATUS",
      "X_AXIS_SUN_VECTOR",
      "Y_AXIS_SUN_VECTOR",
      "Z_AXIS_SUN_VECTOR",
      "EOF1",
      "EOF2",
    ],
    commandParams: ["SOF3", "SOF4", "ID", "EOF1", "EOF2"],
  },
  {
    id: 29,
    command: "ADCS_137_TC_GET_ADCS_MEAS_RATE",
    telemetry: "ADCS_137_TM_GET_ADCS_MEAS_RATE",
    target: "EMULATOR",
    parameters: [
      "SOF3",
      "SOF4",
      "ID",
      "STATUS",
      "Measured_X_Angular_Rate",
      "Measured_Y_Angular_Rate",
      "Measured_Z_Angular_Rate",
      "EOF1",
      "EOF2",
    ],
    commandParams: ["SOF3", "SOF4", "ID", "EOF1", "EOF2"],
  },
  {
    id: 30,
    command: "ADCS_184_TC_GET_ADCS_EST_RATE",
    telemetry: "ADCS_184_TM_GET_ADCS_EST_RATE",
    target: "EMULATOR",
    parameters: [
      "SOF3",
      "SOF4",
      "ID",
      "STATUS",
      "Estimated_X_Angular_Rate",
      "Estimated_Y_Angular_Rate",
      "Estimated_Z_Angular_Rate",
      "EOF1",
      "EOF2",
    ],
    commandParams: ["SOF3", "SOF4", "ID", "EOF1", "EOF2"],
  },
  {
    id: 31,
    command: "ADCS_241_TC_GET_ADCS_EST_ATTITUDE",
    telemetry: "ADCS_241_TM_GET_ADCS_EST_ATTITUDE",
    target: "EMULATOR",
    parameters: [
      "SOF3",
      "SOF4",
      "ID",
      "STATUS",
      "Estimated_Quaternion_1_wrt_ECI",
      "Estimated_Quaternion_2_wrt_ECI",
      "Estimated_Quaternion_3_wrt_ECI",
      "Estimated_Quaternion_4_wrt_ECI",
      "EOF1",
      "EOF2",
    ],
    commandParams: ["SOF3", "SOF4", "ID", "EOF1", "EOF2"],
  },
  {
    id: 32,
    command: "ADCS_177_TC_GET_ADCS_CMD_ATTITUDE",
    telemetry: "ADCS_177_TM_GET_ADCS_CMD_ATTITUDE",
    target: "EMULATOR",
    parameters: [
      "SOF3",
      "SOF4",
      "ID",
      "STATUS",
      "Command_Quaternion_1_wrt_ECI",
      "Command_Quaternion_2_wrt_ECI",
      "Command_Quaternion_3_wrt_ECI",
      "Command_Quaternion_4_wrt_ECI",
      "EOF1",
      "EOF2",
    ],
    commandParams: ["SOF3", "SOF4", "ID", "EOF1", "EOF2"],
  },
  {
    id: 33,
    command: "ADCS_253_TC_ADCS_STATE_CFG",
    telemetry: "ADCS_253_TM_ADCS_STATE_CFG",
    target: "EMULATOR",
    parameters: [
      "SOF3",
      "SOF4",
      "ID",
      "STATUS",
      "Auto_commissioning_flag",
      "RESERVED",
      "EOF1",
      "EOF2",
    ],
    commandParams: ["SOF3", "SOF4", "ID", "EOF1", "EOF2"],
  },
  {
    id: 34,
    command: "ADCS_195_TC_GET_ADCS_RW_SPEED_DATA",
    telemetry: "ADCS_195_TM_GET_ADCS_RW_SPEED_DATA",
    target: "EMULATOR",
    parameters: [
      "SOF3",
      "SOF4",
      "ID",
      "STATUS",
      "Reaction_wheel_instance_ID",
      "Command_Wheel_Speed_1",
      "Command_Wheel_Speed_2",
      "Command_Wheel_Speed_3",
      "Command_Wheel_Speed_4",
      "EOF1",
      "EOF2",
    ],
    commandParams: [
      "SOF3",
      "SOF4",
      "ID",
      "EOF1",
      "EOF2",
      "REACTION_WHEEL_INSTANCE_ID",
    ],
  },
  {
    id: 35,
    command: "ADCS_196_TC_GET_ADCS_RW_SPEED_MEASURE",
    telemetry: "ADCS_196_TM_GET_ADCS_RW_SPEED_MEASURE",
    target: "EMULATOR",
    parameters: [
      "SOF3",
      "SOF4",
      "ID",
      "STATUS",
      "Reaction_wheel_instance_ID",
      "Measured_Wheel_Speed_1",
      "Measured_Wheel_Speed_2",
      "Measured_Wheel_Speed_3",
      "Measured_Wheel_Speed_4",
      "EOF1",
      "EOF2",
    ],
    commandParams: [
      "SOF3",
      "SOF4",
      "ID",
      "EOF1",
      "EOF2",
      "REACTION_WHEEL_INSTANCE_ID",
    ],
  },
  {
    id: 36,
    command: "ADCS_142_TC_GET_ADCS_RW_MAGMTR",
    telemetry: "ADCS_142_TM_GET_ADCS_RW_MAGMTR",
    target: "EMULATOR",
    parameters: [
      "STATUS", "Reaction_wheel_instance_ID", "RW1_Raw_Magnetometer_X_Measurement", "RW1_Raw_Magnetometer_Y_Measurement", "RW1_Raw_Magnetometer_Z_Measurement", "RW2_Raw_Magnetometer_X_Measurement", "RW2_Raw_Magnetometer_Y_Measurement", "RW2_Raw_Magnetometer_Z_Measurement", "RW3_Raw_Magnetometer_X_Measurement", "RW3_Raw_Magnetometer_Y_Measurement", "RW3_Raw_Magnetometer_Z_Measurement", "RW4_Raw_Magnetometer_X_Measurement", "RW4_Raw_Magnetometer_Y_Measurement", "RW4_Raw_Magnetometer_Z_Measurement"
    ],
    commandParams: [
      "SOF3",
      "SOF4",
      "ID",
      "EOF1",
      "EOF2",
      "MAGNETOMETER_INSTANCE_ID",
    ],
  },
  {
    id: 37,
    command: "ADCS_248_TC_GET_ADCS_RAW_CSS",
    telemetry: "ADCS_248_TM_GET_ADCS_RAW_CSS",
    target: "EMULATOR",
    parameters: [
      "SOF3",
      "SOF4",
      "ID",
      "STATUS",
      "CSS_ID",
      "CSS_AD_value_1",
      "CSS_AD_value_2",
      "CSS_AD_value_3",
      "CSS_AD_value_4",
      "CSS_AD_value_5",
      "CSS_AD_value_6",
      "CSS_AD_value_7",
      "CSS_AD_value_8",
      "CSS_AD_value_9",
      "CSS_AD_value_10",
      "CSS_AD_value_11",
      "CSS_AD_value_12",
      "EOF1",
      "EOF2",
    ],
    commandParams: ["SOF3", "SOF4", "ID", "EOF1", "EOF2", "CSS_ID"],
  },
  {
    id: 38,
    command: "ADCS_187_TC_GET_ADCS_MODL_MAG_VEC_DATA",
    telemetry: "ADCS_187_TM_GET_ADCS_MODL_MAG_VEC_DATA",
    target: "EMULATOR",
    parameters: [
      "SOF3",
      "SOF4",
      "ID",
      "STATUS",
      "X_AXIS_MAGNETIC_FIELD_VECTOR",
      "Y_AXIS_MAGNETIC_FIELD_VECTOR",
      "Z_AXIS_MAGNETIC_FIELD_VECTOR",
      "EOF1",
      "EOF2",
    ],
    commandParams: ["SOF3", "SOF4", "ID", "EOF1", "EOF2"],
  },
  {
    id: 39,
    command: "ADCS_188_TC_GET_ADCS_MODL_SUN_VEC_DATA",
    telemetry: "ADCS_188_TM_GET_ADCS_MODL_SUN_VEC_DATA",
    target: "EMULATOR",
    parameters: [
      "SOF3",
      "SOF4",
      "ID",
      "STATUS",
      "X_AXIS_SUN_VECTOR",
      "Y_AXIS_SUN_VECTOR",
      "Z_AXIS_SUN_VECTOR",
      "EOF1",
      "EOF2",
    ],
    commandParams: ["SOF3", "SOF4", "ID", "EOF1", "EOF2", "CSS_ID"],
  },
  {
    id: 40,
    command: "ADCS_181_TC_GET_ADCS_SAT_POS_ECI",
    telemetry: "ADCS_181_TM_GET_ADCS_SAT_POS_ECI",
    target: "EMULATOR",
    parameters: [
      "SOF3",
      "SOF4",
      "ID",
      "STATUS",
      "ECI_Referenced_X_Coordinate",
      "ECI_Referenced_Y_Coordinate",
      "ECI_Referenced_Z_Coordinate",
      "EOF1",
      "EOF2",
    ],
    commandParams: ["SOF3", "SOF4", "ID", "EOF1", "EOF2"],
  },
  {
    id: 41,
    command: "ADCS_182_TC_GET_ADCS_SAT_VELOCITY_DATA",
    telemetry: "ADCS_182_TM_GET_ADCS_SAT_VELOCITY_DATA",
    target: "EMULATOR",
    parameters: [
      "SOF3",
      "SOF4",
      "ID",
      "STATUS",
      "ECI_Referenced_X_Velocity",
      "ECI_Referenced_Y_Velocity",
      "ECI_Referenced_Z_Velocity",
      "EOF1",
      "EOF2",
    ],
    commandParams: ["SOF3", "SOF4", "ID", "EOF1", "EOF2"],
  },
  {
    id: 42,
    command: "ADCS_111_TC_GET_ADCS_ERR_VALID_METRICS",
    telemetry: "ADCS_111_TM_GET_ADCS_ERR_VALID_METRICS",
    target: "EMULATOR",
    parameters: [
      "SOF3",
      "SOF4",
      "ID",
      "STATUS",
      "GOOD_ATTITUDE_TIMER",
      "EIGEN_ERROR",
      "Safe_mode_Sun_Pointing_State",
      "ATTITUDE_VALIDITY",
      "REFERENCE_VALIDITY",
      "TIME_VALIDITY",
      "NUMBER_OF_TRACKER",
      "TRACKER_ATTITUDE_STATUS_1",
      "TRACKER_ATTITUDE_STATUS_2",
      "EOF1",
      "EOF2",
    ],
    commandParams: ["SOF3", "SOF4", "ID", "EOF1", "EOF2"],
  },
  {
    id: 43,
    command: "ADCS_19_TC_FINE_SUN_POINTING",
    telemetry: "ADCS_19_TM_SET_ADCS_CTRL_MODE_CONF",
    target: "EMULATOR",
    parameters: ["SOF3", "SOF4", "ID", "STATUS", "EOF1", "EOF2"],
    commandParams: [
      "SOF3",
      "SOF4",
      "ID",
      "EOF1",
      "EOF2",
      "CONTROL_MODE",
      "TIMEOUT_VALUE_FOR_ASSIGNED_CONTROL_MODE",
      "DEFAULT_CONTROL_MODE",
      "AXIS_SELECTION",
    ],
  },
  {
    id: 44,
    command: "ADCS_19_TC_SUN_POINTING_CONTROL_MODE",
    telemetry: "ADCS_19_TM_SET_ADCS_CTRL_MODE_CONF",
    target: "EMULATOR",
    parameters: ["SOF3", "SOF4", "ID", "STATUS", "EOF1", "EOF2"],
    commandParams: [
      "SOF3",
      "SOF4",
      "ID",
      "EOF1",
      "EOF2",
      "CONTROL_MODE",
      "TIMEOUT_VALUE_FOR_ASSIGNED_CONTROL_MODE",
      "DEFAULT_CONTROL_MODE",
      "RESERVED_SUN_POINTING",
    ],
  },
  {
    id: 45,
    command: "ADCS_19_TC_NADIR_POINTING",
    telemetry: "ADCS_19_TM_SET_ADCS_CTRL_MODE_CONF",
    target: "EMULATOR",
    parameters: ["SOF3", "SOF4", "ID", "STATUS", "EOF1", "EOF2"],
    commandParams: [
      "SOF3",
      "SOF4",
      "ID",
      "EOF1",
      "EOF2",
      "CONTROL_MODE",
      "TIMEOUT_VALUE_FOR_ASSIGNED_CONTROL_MODE",
      "DEFAULT_CONTROL_MODE",
    ],
  },
  {
    id: 46,
    command: "ADCS_19_TC_TARGET_TRACKING_CONTROL_MODE_ECEF_TARGET_REFERENCE",
    telemetry: "ADCS_19_TM_SET_ADCS_CTRL_MODE_CONF",
    target: "EMULATOR",
    parameters: ["SOF3", "SOF4", "ID", "STATUS", "EOF1", "EOF2"],
    commandParams: [
      "SOF3",
      "SOF4",
      "ID",
      "EOF1",
      "EOF2",
      "CONTROL_MODE",
      "TIMEOUT_VALUE_FOR_ASSIGNED_CONTROL_MODE",
      "DEFAULT_CONTROL_MODE",
      "ECEF_TARGET_REFERENCE_TYPE",
      "VELOCITY_ABERRATION",
      "REFERENCE_FRAME_X_DESIRED_DIRECTION",
      "TARGET_ECEF_GEOCENTRIC_X_POSITION",
      "TARGET_ECEF_GEOCENTRIC_Y_POSITION",
      "TARGET_ECEF_GEOCENTRIC_Z_POSITION",
      "HEADING_OR_BEARING_ANGLE",
      "BODY_FIXED_COMMAND_FRAME_Z_DIRECTION",
      "BODY_FIXED_COMMAND_FRAME_X_DIRECTION",
    ],
  },
  {
    id: 47,
    command: "ADCS_19_TC_TARGET_TRACKING_CONTROL_MODE_WITH_ADDITIONAL_CONTROL",
    telemetry: "ADCS_19_TM_SET_ADCS_CTRL_MODE_CONF",
    target: "EMULATOR",
    parameters: ["SOF3", "SOF4", "ID", "STATUS", "EOF1", "EOF2"],
    commandParams: [
      "SOF3",
      "SOF4",
      "ID",
      "EOF1",
      "EOF2",
      "CONTROL_MODE",
      "TIMEOUT_VALUE_FOR_ASSIGNED_CONTROL_MODE",
      "DEFAULT_CONTROL_MODE",
      "WITH_ADDITIONAL_CONTROL_TARGET_REFERENCE_TYPE",
      "VELOCITY_ABERRATION",
      "REFERENCE_FRAME_X_DESIRED_DIRECTION",
      "REFERENCE_FRAME_Z_DESIRED_DIRECTION",
      "TARGET_X_COORDINATES",
      "TARGET_Y_COORDINATES",
      "TARGET_Z_COORDINATES",
      "HEADING_OR_BEARING_ANGLE",
      "BODY_FIXED_COMMAND_FRAME_Z_DIRECTION",
      "BODY_FIXED_COMMAND_FRAME_X_DIRECTION",
      "ATTITUDE_INTERPRETATION",
      "QUATERNION_1_OR_ROLL",
      "QUATERNION_2_OR_PITCH",
      "QUATERNION_3_OR_YAW",
      "QUATERNION_4_SCALER_ELEMENT",
      "RATE_INTERPRETATION",
      "COMMANDED_X_AXIS_RATE",
      "COMMANDED_Y_AXIS_RATE",
      "COMMANDED_Z_AXIS_RATE",
      "TAI_TIME_TO_EXECUTE_COMMANDED_RATE",
      "5HZ_ADCS_CYCLE_WITHIN_1_SEC",
    ],
  },
  {
    id: 48,
    command: "OBC_610_TC_GET_TEMP",
    telemetry: "OBC_610_TM_GET_TEMP",
    target: "EMULATOR",
    parameters: ["DEVICE_ID", "TEMPERATURE"],
    commandParams: ["DEVICE_ID"],
  },
  {
    id: 49,
    command: "OBC_611_TC_GET_TIME",
    telemetry: "OBC_611_TM_GET_TIME",
    target: "EMULATOR",
    parameters: ["DEVICE_ID", "MCU_UPTIME", "EPOCH_TIME"],
    commandParams: ["DEVICE_ID"],
  },

  {
    id: 50,
    command: "OBC_545_TC_PLD_VM_PWR_ON",
    telemetry: "OBC_545_TM_PLD_VM_PWR_ON",
    target: "EMULATOR",
    parameters: ["STATUS"],
    commandParams: ["VIRTUAL_MACHINE_ID"],
  },
  {
    id: 51,
    command: "OBC_546_TC_PLD_VM_PWR_OFF",
    telemetry: "OBC_546_TM_PLD_VM_PWR_OFF",
    target: "EMULATOR",
    parameters: ["STATUS"],
    commandParams: [
      "VIRTUAL_MACHINE_ID",
      "SHUTDOWN_TIME_MIN",
      "SHUTDOWN_TIME_SEC",
      "SHUTDOWN_TIME_MSEC",
      "SHUTDOWN_PURPOSE",
    ],
  },
  {
    id: 52,
    command: "OBC_508_TC_CONFIG_AUTO_LEOP_TRIGGER_TMR",
    telemetry: "OBC_508_TM_CONFIG_AUTO_LEOP_TRIGGER_TMR",
    target: "EMULATOR",
    parameters: ["Response_Status"],
    commandParams: ["TIMER_CONFIGURATION_VALUE"],
  },
  {
    id: 53,
    command: "OBC_508_TC_TRIGGER_HINGE_PROCESS",
    telemetry: "OBC_508_TM_TRIGGER_HINGE_PROCESS",
    target: "EMULATOR",
    parameters: ["Response"],
    commandParams: [],
  },
  {
    id: 54,
    command: "OBC_505_TC_GET_AUTO_LEOPS_STATE",
    telemetry: "OBC_505_TC_GET_AUTO_LEOPS_STATE",
    target: "EMULATOR",
    parameters: ["Satellite_Body_Axis_1"],
    commandParams: [],
  },
  {
    id: 55,
    command: "OBC_602_TC_TRIGGER_HINGE_PROCESS",
    telemetry: "OBC_602_TM_TRIGGER_HINGE_PROCESS",
    target: "EMULATOR",
    parameters: ["Response"],
    commandParams: [],
  },
  {
    id: 56,
    command: "EPS_200_TC_GET_SUB_SYS_INFO",
    telemetry: "200_EPS_TM_GET_SUB_SYS_INFO",
    target: "EMULATOR",
    parameters: [
      "FIRMWARE_VERSION",
      "SAS_B",
      "BURN_WIRE_2",
      "AVIONICS",
      "RESERVED_SS_1",
      "RESERVED_SS_2",
      "RESERVED_SS_3",
      "RESERVED_SS_4",
      "RESERVED_SS_5",
      "SECONDARY_EDGE_SERVER",
      "PRIMARY_THRUSTER",
      "RESERVED_SS_6",
      "MSI",
      "SES_A",
      "SES_B",
      "SAS_A",
      "BURN_WIRE_1",
      "RESERVED",
      "PRIMARY_UHF",
      "RESERVED_SS_7",
      "PRIMARY_S_BAND",
      "RESERVED_SS_8",
      "PRIMARY_X_BAND",
      "SECONDARY_X_BAND",
      "PRIMARY_EDGE_SERVER",
      "HOLD_AND_RELEASE_MODULE",
      "PRIMARY_OBC",
      "SECONDARY_OBC",
      "PRIMARY_PAYLOAD_SERVER",
      "SECONDARY_PAYLOAD_SERVER",
      "PRIMARY_GPS",
      "SECONDARY_GPS",
      "PRIMARY_ADCS",
      "TOTAL_VALID_SUB_SYSTEM",
      "HRM",
      "OBC",
      "OBC_2",
      "PL_SERVER",
      "PL_SERVER_2",
      "GPS",
      "GPS_2",
      "ADCS",
      "UHF",
      "S_BAND",
      "X_BAND",
      "X_BAND_2",
      "EDGE",
      "EDGE_2",
      "THRUSTER",
      "MSI_SS",
      "SES_A_SS",
      "SES_B_SS",
      "SAS_A_SS",
      "UHF_BURN_WIRE",
      "SAS_B_SS",
      "AVIONICS_SS",
      "RESERVED_EPS",
      "SIZE_OF_PAYLOAD_STREAM",
      "SOLAR_PANEL_COUNT",
      "SOLAR_PANEL_TEMP_SENSOR_COUNT",
      "MPPT_COUNT",
      "OUTPUT_CONVERTOR_COUNT",
      "BATTERY_COUNT",
      "BATTERY_TEMP_SENSOR_COUNT",
      "POWER_SUPPLY_CHANNEL",
      "RESERVED_EPS_4",
      "OBC_RESET_COUNT",
      "OUTPUT_CHANNEL_RESET_COUNT",
      "SOLAR_PANEL_VOLTAGE_1",
      "SOLAR_PANEL_VOLTAGE_2",
      "SOLAR_PANEL_VOLTAGE_3",
      "SOLAR_PANEL_VOLTAGE_4",
      "SOLAR_PANEL_VOLTAGE_5",
      "SOLAR_PANEL_VOLTAGE_6",
      "SOLAR_PANEL_VOLTAGE_7",
      "SOLAR_PANEL_VOLTAGE_8",
      "SOLAR_PANEL_VOLTAGE_9",
      "SOLAR_PANEL_CURRENT_1",
      "SOLAR_PANEL_CURRENT_2",
      "SOLAR_PANEL_CURRENT_3",
      "SOLAR_PANEL_CURRENT_4",
      "SOLAR_PANEL_CURRENT_5",
      "SOLAR_PANEL_CURRENT_6",
      "SOLAR_PANEL_CURRENT_7",
      "SOLAR_PANEL_CURRENT_8",
      "SOLAR_PANEL_CURRENT_9",
      "SOLAR_PANEL_TEMP_1",
      "SOLAR_PANEL_TEMP_2",
      "SOLAR_PANEL_TEMP_3",
      "SOLAR_PANEL_TEMP_4",
      "SOLAR_PANEL_TEMP_5",
      "OUTPUT_CONVERTOR_VOLTAGE_1",
      "OUTPUT_CONVERTOR_VOLTAGE_2",
      "OUTPUT_CONVERTOR_VOLTAGE_3",
      "OUTPUT_CONVERTOR_VOLTAGE_4",
      "OUTPUT_CONVERTOR_VOLTAGE_5",
      "BATTERY_VOLTAGE",
      "BATTERY_CURRENT",
      "BATTERY_TEMP_SENSOR_1",
      "BATTERY_TEMP_SENSOR_2",
      "BATTERY_TEMP_SENSOR_3",
      "BATTERY_TEMP_SENSOR_4",
      "BATTERY_TEMP_SENSOR_5",
      "BATTERY_TEMP_SENSOR_6",
      "BATTERY_TEMP_SENSOR_7",
      "BATTERY_TEMP_SENSOR_8",
      "BATTERY_TEMP_SENSOR_9",
      "BATTERY_TEMP_SENSOR_10",
      "BATTERY_TEMP_SENSOR_11",
      "BATTERY_TEMP_SENSOR_12",
      "BATTERY_TEMP_SENSOR_13",
      "BATTERY_TEMP_SENSOR_14",
      "BATTERY_TEMP_SENSOR_15",
      "BATTERY_TEMP_SENSOR_16",
      "BATTERY_TEMP_SENSOR_17",
      "BATTERY_TEMP_SENSOR_18",
      "BATTERY_TEMP_SENSOR_19",
      "BATTERY_TEMP_SENSOR_20",
      "BATTERY_TEMP_SENSOR_21",
      "BATTERY_TEMP_SENSOR_22",
      "BATTERY_TEMP_SENSOR_23",
      "BATTERY_TEMP_SENSOR_24",
      "OBC_PRI",
      "OBC_2",
      "PL_8_PRI_PORT",
      "ADCS_PRI_PORT",
      "THRUSTER_PRI_PORT",
      "THRUSTER_PRI_PORT_2",
      "THRUSTER_HTR_PORT",
      "UHF_PRI_PORT",
      "S_BAND_PRI_PORT",
      "X_BAND_2_PRI_PORT",
      "X_BAND_PRI_PORT",
      "PL_1_PRI_PORT_11",
      "PL_2_PRI_PORT_AND_PL_3_HTR_PORT",
      "PL_2_PRI_PORT_13",
      "PL_3_PRI_PORT_14",
      "HRM_PRI_PORT_15",
      "HRM_PRI_PORT_16",
      "HRM_PRI_PORT_17",
      "HRM_PRI_PORT_18",
      "HRM_PRI_PORT_19",
      "HRM_PRI_PORT_20",
      "HRM_PRI_PORT_21",
      "HRM_PRI_PORT_22",
      "PL_4_PRI_PORT_23",
      "PL_4_HTR_PORT_24",
      "PL_4_PRI_PORT_25",
      "OBC_RED_PORT_26",
      "OBC_2_RED_PORT_27",
      "PL_8_RED_PORT_28",
      "ADCS_RED_PORT_29",
      "THRUSTER_RED_PORT_30",
      "THRUSTER_RED_PORT_31",
      "THRUSTER_HTR_RD_PORT_32",
      "UHF_RED_PORT_33",
      "S_BAND_RED_PORT_34",
      "X_BAND_2_RED_PORT_35",
      "X_BAND_RED_PORT_36",
      "PL_1_RED_PORT_37",
      "PL_2_HTR_RD_AND_PL_3_HTR_RD_PORT_38",
      "PL_2_RED_PORT_39",
      "PL_3_RED_PORT_40",
      "HRM_RED_PORT_41",
      "HRM_RED_PORT_42",
      "HRM_RED_PORT_43",
      "HRM_RED_PORT_44",
      "HRM_RED_PORT_45",
      "HRM_RED_PORT_46",
      "HRM_RED_PORT_47",
      "HRM_RED_PORT_48",
      "PL_6_PRI_PORT_49",
      "PL_6_HTR_PORT_50",
      "PL_5_RED_PORT_51",
      "CHANNEL_res_1",
      "CHANNEL_res_2",
      "CHANNEL_res_3",
      "CHANNEL_res_4",

      "CURRENT_CONSUMPTION_OBC",
      "CURRENT_CONSUMPTION_OBC_2",
      "CURRENT_CONSUMPTION_PL_8_PRI_PORT",
      "CURRENT_CONSUMPTION_ADCS_PRI_PORT",
      "CURRENT_CONSUMPTION_THRUSTER_PRI_PORT",
      "CURRENT_CONSUMPTION_THRUSTER_PRI_PORT_2",
      "CURRENT_CONSUMPTION_THRUSTER_HTR_PORT",
      "CURRENT_CONSUMPTION_UHF_PRI_PORT",
      "CURRENT_CONSUMPTION_S_BAND_PRI_PORT",
      "CURRENT_CONSUMPTION_X_BAND_2_PRI_PORT",
      "CURRENT_CONSUMPTION_X_BAND_PRI_PORT",
      "CURRENT_CONSUMPTION_PL_1_PRI_PORT_11",
      "CURRENT_CONSUMPTION_PL_2_PRI_PORT_AND_PL_3_HTR_PORT",
      "CURRENT_CONSUMPTION_PL_2_PRI_PORT_13",
      "CURRENT_CONSUMPTION_PL_3_PRI_PORT_14",
      "CURRENT_CONSUMPTION_HRM_PRI_PORT_15",
      "CURRENT_CONSUMPTION_HRM_PRI_PORT_16",
      "CURRENT_CONSUMPTION_HRM_PRI_PORT_17",
      "CURRENT_CONSUMPTION_HRM_PRI_PORT_18",
      "CURRENT_CONSUMPTION_HRM_PRI_PORT_19",
      "CURRENT_CONSUMPTION_HRM_PRI_PORT_20",
      "CURRENT_CONSUMPTION_HRM_PRI_PORT_21",
      "CURRENT_CONSUMPTION_HRM_PRI_PORT_22",
      "CURRENT_CONSUMPTION_PL_4_PRI_PORT_23",
      "CURRENT_CONSUMPTION_PL_4_HTR_PORT_24",
      "CURRENT_CONSUMPTION_PL_4_PRI_PORT_25",
      "CURRENT_CONSUMPTION_OBC_RED_PORT_26",
      "CURRENT_CONSUMPTION_OBC_2_RED_PORT_27",
      "CURRENT_CONSUMPTION_PL_8_RED_PORT_28",
      "CURRENT_CONSUMPTION_ADCS_RED_PORT_29",
      "CURRENT_CONSUMPTION_THRUSTER_RED_PORT_30",
      "CURRENT_CONSUMPTION_THRUSTER_RED_PORT_31",
      "CURRENT_CONSUMPTION_THRUSTER_HTR_RD_PORT_32",
      "CURRENT_CONSUMPTION_UHF_RED_PORT_33",
      "CURRENT_CONSUMPTION_S_BAND_RED_PORT_34",
      "CURRENT_CONSUMPTION_X_BAND_2_RED_PORT_35",
      "CURRENT_CONSUMPTION_X_BAND_RED_PORT_36",
      "CURRENT_CONSUMPTION_PL_1_RED_PORT_37",
      "CURRENT_CONSUMPTION_PL_2_HTR_RD_AND_PL_3_HTR_RD_PORT_38",
      "CURRENT_CONSUMPTION_PL_2_RED_PORT_39",
      "CURRENT_CONSUMPTION_PL_3_RED_PORT_40",
      "CURRENT_CONSUMPTION_HRM_RED_PORT_41",
      "CURRENT_CONSUMPTION_HRM_RED_PORT_42",
      "CURRENT_CONSUMPTION_HRM_RED_PORT_43",
      "CURRENT_CONSUMPTION_HRM_RED_PORT_44",
      "CURRENT_CONSUMPTION_HRM_RED_PORT_45",
      "CURRENT_CONSUMPTION_HRM_RED_PORT_46",
      "CURRENT_CONSUMPTION_HRM_RED_PORT_47",
      "CURRENT_CONSUMPTION_HRM_RED_PORT_48",
      "CURRENT_CONSUMPTION_PL_6_PRI_PORT_49",
      "CURRENT_CONSUMPTION_PL_6_HTR_PORT_50",
      "CURRENT_CONSUMPTION_PL_5_RED_PORT_51",
      "CURRENT_STATUS_OBC",
      "CURRENT_STATUS_OBC_2",
      "CURRENT_STATUS_PL_8_PRI_PORT",
      "CURRENT_STATUS_ADCS_PRI_PORT",
      "CURRENT_STATUS_THRUSTER_PRI_PORT",
      "CURRENT_STATUS_THRUSTER_PRI_PORT_2",
      "CURRENT_STATUS_THRUSTER_HTR_PORT",
      "CURRENT_STATUS_UHF_PRI_PORT",
      "CURRENT_STATUS_S_BAND_PRI_PORT",
      "CURRENT_STATUS_X_BAND_2_PRI_PORT",
      "CURRENT_STATUS_X_BAND_PRI_PORT",
      "CURRENT_STATUS_PL_1_PRI_PORT_11",
      "CURRENT_STATUS_PL_2_PRI_PORT_AND_PL_3_HTR_PORT",
      "CURRENT_STATUS_PL_2_PRI_PORT_13",
      "CURRENT_STATUS_PL_3_PRI_PORT_14",
      "CURRENT_STATUS_HRM_PRI_PORT_15",
      "CURRENT_STATUS_HRM_PRI_PORT_16",
      "CURRENT_STATUS_HRM_PRI_PORT_17",
      "CURRENT_STATUS_HRM_PRI_PORT_18",
      "CURRENT_STATUS_HRM_PRI_PORT_19",
      "CURRENT_STATUS_HRM_PRI_PORT_20",
      "CURRENT_STATUS_HRM_PRI_PORT_21",
      "CURRENT_STATUS_HRM_PRI_PORT_22",
      "CURRENT_STATUS_PL_4_PRI_PORT_23",
      "CURRENT_STATUS_PL_4_HTR_PORT_24",
      "CURRENT_STATUS_PL_4_PRI_PORT_25",
      "CURRENT_STATUS_OBC_RED_PORT_26",
      "CURRENT_STATUS_OBC_2_RED_PORT_27",
      "CURRENT_STATUS_PL_8_RED_PORT_28",
      "CURRENT_STATUS_ADCS_RED_PORT_29",
      "CURRENT_STATUS_THRUSTER_RED_PORT_30",
      "CURRENT_STATUS_THRUSTER_RED_PORT_31",
      "CURRENT_STATUS_THRUSTER_HTR_RD_PORT_32",
      "CURRENT_STATUS_UHF_RED_PORT_33",
      "CURRENT_STATUS_S_BAND_RED_PORT_34",
      "CURRENT_STATUS_X_BAND_2_RED_PORT_35",
      "CURRENT_STATUS_X_BAND_RED_PORT_36",
      "CURRENT_STATUS_PL_1_RED_PORT_37",
      "CURRENT_STATUS_PL_2_HTR_RD_AND_PL_3_HTR_RD_PORT_38",
      "CURRENT_STATUS_PL_2_RED_PORT_39",
      "CURRENT_STATUS_PL_3_RED_PORT_40",
      "CURRENT_STATUS_HRM_RED_PORT_41",
      "CURRENT_STATUS_HRM_RED_PORT_42",
      "CURRENT_STATUS_HRM_RED_PORT_43",
      "CURRENT_STATUS_HRM_RED_PORT_44",
      "CURRENT_STATUS_HRM_RED_PORT_45",
      "CURRENT_STATUS_HRM_RED_PORT_46",
      "CURRENT_STATUS_HRM_RED_PORT_47",
      "CURRENT_STATUS_HRM_RED_PORT_48",
      "CURRENT_STATUS_PL_6_PRI_PORT_49",
      "CURRENT_STATUS_PL_6_HTR_PORT_50",
      "CURRENT_STATUS_PL_5_RED_PORT_51",
      "CHANNEL_res_cur_1",
      "CHANNEL_res_cur_2",
      "CHANNEL_res_cur_3",
      "CHANNEL_res_cur_4",
      "UHF_ANTENNA_RELEASE_STATUS",
      "SECONDARY_HDRM_RELEASE_STATUS",
      "PRIMARY_HDRM_RELEASE_STATUS",
      "HDRM_RESERVED_2",
      "HDRM_RESERVED_1",
      "BATTERY_MODE",
      "Reserved_hdrm",
      "RBF_STATUS",
    ],
    commandParams: [],
  },
  {
    id: 57,
    command: "EPS_216_TC_SET_EPS_CTRL_DEV_TMR",
    telemetry: "216_EPS_TM_SET_EPS_CTRL_DEV_TMR",
    target: "EMULATOR",
    parameters: ["STATUS"],
    commandParams: [
      "VALID_STATE_COUNT",
      "CHANNEL_NUMBER_OF_HDRM",
      "HDRM_POWER_ON_DURATION",
      "COOLING_PERIOD",
      "NUMBER_OF_TRAILS",
      "RESERVED_1",
      "RESERVED_2",
    ],
  },
  {
    id: 58,
    command: "EPS_217_TC_GET_EPS_CTRL_DEV_TMR",
    telemetry: "217_EPS_TM_GET_EPS_CTRL_DEV_TMR",
    target: "EMULATOR",
    parameters: [
      "STATUS",
      "CHANNEL_NUMBER_OF_HDRM",
      "HDRM_POWER_ON_DURATION",
      "COOLING_PERIOD",
      "NO_OF_TRAILS",
      "RESERVED_1",
      "RESERVED_2",
      "RESERVED_3",
    ],
    commandParams: ["CHANNEL_NUMBER_OF_HDRM"],
  },
  {
    id: 59,
    command: "EPS_211_TC_SET_DEVICE_STS",
    telemetry: "211_EPS_TM_SET_DEVICE_STS",
    target: "EMULATOR",
    parameters: ["STATUS", "SUB_SYSTEM_ID", "POWER_STATE"],
    commandParams: ["CHANNEL_NO", "CHANNEL_STATE"],
  },
  {
    id: 60,
    command: "202_TC_SET_EPS_CONF_OPTION_1",
    telemetry: "OBC_602_TM_TRIGGER_HINGE_PROCESS",
    target: "EMULATOR",
    parameters: ["Response"],
    commandParams: [],
  },
  {
    id: 61,
    command: "EPS_212_TC_GET_DEVICE_STS",
    telemetry: "212_EPS_TM_GET_DEVICE_STS",
    target: "EMULATOR",
    parameters: [
      "STATUS",
      "SAS_B",
      "BURN_WIRE_2",
      "AVIONICS",
      "RESERVED_SS_1",
      "RESERVED_SS_2",
      "RESERVED_SS_3",
      "RESERVED_SS_4",
      "RESERVED_SS_5",
      "SECONDARY_EDGE_SERVER",
      "PRIMARY_THRUSTER",
      "RESERVED_SS_6",
      "MSI",
      "SES_A",
      "SES_B",
      "SAS_A",
      "BURN_WIRE_1",
      "RESERVED",
      "PRIMARY_UHF",
      "RESERVED_SS_7",
      "PRIMARY_S_BAND",
      "RESERVED_SS_8",
      "PRIMARY_X_BAND",
      "SECONDARY_X_BAND",
      "PRIMARY_EDGE_SERVER",
      "HOLD_AND_RELEASE_MODULE",
      "PRIMARY_OBC",
      "SECONDARY_OBC",
      "PRIMARY_PAYLOAD_SERVER",
      "SECONDARY_PAYLOAD_SERVER",
      "PRIMARY_GPS",
      "SECONDARY_GPS",
      "PRIMARY_ADCS",

      "HOLD_AND_RELEASE_MODULE_SS",

      "PRIMARY_ON_BOARD_CONTROLLER",
      "SECONDARY_ON_BOARD_CONTROLLER",

      "PRIMARY_PAYLOAD_SERVER_SS",
      "SECONDARY_PAYLOAD_SERVER_SS",
      "PRIMARY_GPS_SS",
      "SECONDARY_GPS_SS",
      "PRIMARY_ADCS_SS",

      "PRIMARY_UHF_SS",
      "PRIMARY_S_BAND_SS",
      "PRIMARY_X_BAND_SS",
      "SECONDARY_X_BAND_SS",
      "PRIMARY_EDGE_SERVER_SS",
      "SECONDARY_EDGE_SERVER_SS",
      "PRIMARY_THRUSTER_SS",

      "RESERVED_1",
      "RESERVED_2",
      "RESERVED_3",
      "RESERVED_4",
      "RESERVED_5",
      "RESERVED_6",
      "RESERVED_7",

      "PL_1_MSI",
      "PL_2_SES_A",
      "PL_3_SES_B",
      "PL_4_SAS_A",
      "PL_5_BURN_WIRE",
      "PL_6_SAS_B",
      "PL_8_AVIONICS",
    ],
    commandParams: [],
  },
  {
    id: 62,
    command: "COMMS_350_TC_GET_SBAND_TX_CFG",
    telemetry: "COMMS_350_TM_GET_SBAND_TX_CFG",
    target: "EMULATOR",
    parameters: [
      "Transmit_frequency",
      "Transmit_modulation_type",
      "Transmit_symbol_rate",
      "Reserved_9",
      "Transmit_power",
      "Reserved_14",
      "Enable_Reed_Solomon",
      "Enable_BCH",
      "Enable_randomization",
      "Reserved_18",
      "Reserved_19",
      "Maximum_payload_size",
      "Reserved_23",
      "Reserved_25",
      "Reserved_60",
      "Reserved_61",
      "Reserved_65",
      "Reserved_69",
    ],
    commandParams: [],
  },
  {
    id: 63,
    command: "COMMS_369_TC_GET_SBAND_RX_CFG",
    telemetry: "COMMS_369_TM_GET_SBAND_RX_CFG",
    target: "EMULATOR",
    parameters: [
      "Receive_frequency",
      "Receive_modulation_type",
      "Receive_symbol_rate",
      "Reserved_9",
      "Reserved_10",
      "Reserved_15",
      "Enable_convolutional_coding",
      "Enable_randomization",
      "Reserved_18",
      "Reserved_19",
      "Reserved_21",
      "Reserved_23",
      "Reserved_58",
      "Reserved_62",
      "Reserved_66",
      "Reserved_70",
      "Reserved_74",
      "Reserved_78",
      "Reserved_82",
      "Reserved_83",
    ],
    commandParams: [],
  },
  {
    id: 64,
    command: "COMMS_420_TC_SBAND_GET_RX_SEL_CFG",
    telemetry: "COMMS_420_TM_SBAND_GET_RX_SEL_CFG",
    target: "EMULATOR",
    parameters: ["RECEIVER_PORT_SELECTION"],
    commandParams: [],
  },
  {
    id: 65,
    command: "COMMS_463_TC_SBAND_GET_DEVICE_CONF",
    telemetry: "OBC_602_TM_TRIGGER_HINGE_PROCESS",
    target: "EMULATOR",
    parameters: ["Response"],
    commandParams: [],
  },
  {
    id: 66,
    command: "COMMS_465_TC_SBAND_GET_COMMS_TM_INFO",
    telemetry: "COMMS_465_TM_SBAND_GET_COMMS_TM_INFO",
    target: "EMULATOR",
    parameters: [
      "Reserved_0",
      "Reserved_1",
      "Reserved_2",
      "HK_Reserved_3",

      "SDR_Temp_Transceiver",
      "SDR_Temp_EthPhy",
      "SDR_Temp_FPGA",
      "SDR_Temp_Reserved",

      "Rcv0_HW_Active",
      "Rcv0_SYNC",
      "Rcv0_Gain",
      "Rcv0_Min_SIR",
      "Rcv0_Max_SIR",
      "Rcv0_Reserved_57",
      "Rcv0_Reserved_58",
      "Rcv0_Min_PWR",
      "Rcv0_Max_PWR",
      "Rcv0_Reserved_60",
      "Rcv0_Reserved_61",
      "Rcv0_BCH_Count",
      "Rcv0_BCH_Error_Count",

      "Rcv1_HW_Active",
      "Rcv1_SYNC",
      "Rcv1_Gain",
      "Rcv1_Min_SIR",
      "Rcv1_Max_SIR",
      "Rcv1_Reserved_73",
      "Rcv1_Reserved_74",
      "Rcv1_Reserved_75a",
      "Rcv1_Reserved_75b",
      "Rcv1_Reserved_76",
      "Rcv1_Reserved_77",
      "Rcv1_BCH_Count",
      "Rcv1_BCH_Error_Count",

      "Xmt0_HW_Active",
      "Xmt0_Modulation",
      "Xmt0_FEC",
      "Xmt0_Attenuation",
      "Xmt0_Reserved",

      "Xmt1_HW_Active",
      "Xmt1_Modulation",
      "Xmt1_FEC",
      "Xmt1_Attenuation",
      "Xmt1_Reserved",

      "Reserved_95",
    ],
    commandParams: [],
  },
  {
    id: 67,
    command: "COMMS_468_TC_SBAND_GET_PROD_KEY",
    telemetry: "COMMS_468_TM_SBAND_GET_PROD_KEY",
    target: "EMULATOR",
    parameters: ["Old_Product_Key", "Current_Product_Key"],
    commandParams: [],
  },
  {
    id: 68,
    command: "PS_600_TC_PLD_START_SEQUENCE",
    telemetry: "PS_600_TM_PLD_START_SEQUENCE",
    target: "EMULATOR",
    parameters: ["Sequence_Response"],
    commandParams: ["DESTINATION_APP_ID", "SEQUENCE_ID", "SEQUENCE_PARAMETERS", "DADLINE_MIN", "DADLINE_MAX", "DADLINE_MILLISECONDS"],
  },
  {
    id: 69,
    command: "PS_604_TC_PLD_HEALTH_STATUS_CMD",
    telemetry: "PS_604_TM_PLD_HEALTH_STATUS_CMD",
    target: "EMULATOR",
    parameters: ["Application_State", "Total_storage_in_KB", "Total_storage_of_App_folder_in_KB", "Total_storage_of_config_folder_in_KB", "Total_storage_of_inbound_folder_in_KB", "Total_storage_of_outbound_folder_in_KB", "Total_storage_of_factory_image_used_in_KB"],
    commandParams: ["DESTINATION_APP_ID"],
  },
  {
    id: 70,
    command: "PS_605_TC_PS_HEALTH_STATUS_CMD",
    telemetry: "PS_605_TM_PS_HEALTH_STATUS_CMD",
    target: "EMULATOR",
    parameters: ["CPU_USAGE", "TOTAL_MEMORY", "FREE_MEMORY", "USED_MEMORY", "TOTAL_STORAGE_IN_MB", "USED_STORAGE_IN_MB", "PAYLOAD_SERVER_UTC_CURRENT_TIME_IN_MINUTES"],
    commandParams: [],
  },
  {
    id: 71,
    command: "PS_606_TC_PLD_UPDATE_DB_CMD",
    telemetry: "PS_606_TM_PLD_UPDATE_DB_CMD",
    target: "EMULATOR",
    parameters: ["RESPONSE"],
    commandParams: ["DATABASE_FILE_INDEX"],
  },
  {
    id: 72,
    command: "PS_607_TC_PLD_GET_DB_CMD",
    telemetry: "PS_607_TM_PLD_GET_DB_CMD",
    target: "EMULATOR",
    parameters: ["RESPONSE"],
    commandParams: ["DATABASE_FILE_INDEX"],
  },
  {
    id: 73,
    command: "PS_608_TC_PLD_RESTORE_FACTORY_DATABASE_CMD",
    telemetry: "PS_608_TC_PLD_RESTORE_FACTORY_DATABASE_CMD",
    target: "EMULATOR",
    parameters: ["RESPONSE"],
    commandParams: ["DATABASE_FILE_INDEX"],
  },
  {
    id: 74,
    command: "PS_609_TC_PLD_GET_IMAGE_TAG_CMD",
    telemetry: "PS_609_TM_PLD_GET_IMAGE_TAG_CMD",
    target: "EMULATOR",
    parameters: ["Tags"],
    commandParams: ["DESTINATION_APP_ID"],
  },
  {
    id: 75,
    command: "PS_610_TC_PLD_UPGRADE_PLD_CMD",
    telemetry: "PS_610_TM_PLD_UPGRADE_PLD_CMD",
    target: "EMULATOR",
    parameters: ["RESPONSE"],
    commandParams: ["DESTINATION_APP_ID", "OPERATIONS"],
  },
  {
    id: 76,
    command: "PS_611_TC_PLD_UPDATE_FACTORY_IMAGE_CMD",
    telemetry: "PS_611_TM_PLD_UPDATE_FACTORY_IMAGE_CMD",
    target: "EMULATOR",
    parameters: ["RESPONSE"],
    commandParams: ["DESTINATION_APP_ID", "OPERATIONS"],
  },
  {
    id: 77,
    command: "PS_612_TC_PLD_RESTORE_FACTORY_IMAGE_CMD",
    telemetry: "PS_612_TM_PLD_UPDATE_FACTORY_IMAGE_CMD",
    target: "EMULATOR",
    parameters: ["RESPONSE"],
    commandParams: ["DESTINATION_APP_ID", "OPERATIONS"],
  },
  {
    id: 78,
    command: "PS_613_TC_PC_UPDATE_IMAGE_CMD",
    telemetry: "PS_613_TM_PC_UPDATE_IMAGE_CMD",
    target: "EMULATOR",
    parameters: ["RESPONSE"],
    commandParams: [],
  },
  {
    id: 79,
    command: "PS_614_TC_PLD_STATSD_CMD",
    telemetry: "PS_614_TM_PLD_STATSD_CMD",
    target: "EMULATOR",
    parameters: ["App_ID", "Number_of_valid_counters_from_metrics_array", "Timestamps", "Counter_Number_1", "Counter_Number_2", "Counter_Number_3", "Counter_Number_4", "Counter_Number_5", "Counter_Number_6", "Counter_Number_7", "Counter_Number_8", "Counter_Name_1", "Counter_Name_2", "Counter_Name_3", "Counter_Name_4", "Counter_Name_5", "Counter_Name_6", "Counter_Name_7", "Counter_Name_8",],
    commandParams: ["DESTINATION_APP_ID"],
  },
  {
    id: 80,
    command: "PS_615_TC_CHANGE_FTM_CONFIG_CMD",
    telemetry: "PS_615_TM_CHANGE_FTM_CONFIG_CMD",
    target: "EMULATOR",
    parameters: ["RESPONSE"],
    commandParams: ["RADIO_ID", "FTDS_DELAY", "MTU", "RX_CONNECTION_FAILURE", "ENABLE_SEQUENCE_LOSS_DETECTION", "ACTIVITY_CHECK",],
  },
  {
    id: 81,
    command: "OBC_621_TC_GET_HEALTH_METRICS_ONE_SUBMODULE_ONE_QUEUE",
    telemetry: "",
    target: "EMULATOR",
    parameters: [""],
    commandParams: [],
  },
  {
    id: 82,
    command: "OBC_621_TC_GET_HEALTH_METRICS_ONE_SUBMODULE_MULTIPLE_QUEUES",
    telemetry: "",
    target: "EMULATOR",
    parameters: [""],
    commandParams: [],
  },
  {
    id: 83,
    command: "OBC_621_TC_GET_HEALTH_METRICS_PRIORITY_BASED_QUEUES_IN_ALL_SUBMODULES",
    telemetry: "",
    target: "EMULATOR",
    parameters: [""],
    commandParams: [],
  },
  {
    id: 84,
    command: "OBC_1042_TC_EXOTRAIL_GET_PRPLT_TANK_TEMP",
    telemetry: "OBC_1042_TM_EXOTRAIL_GET_PRPLT_TANK_TEMP",
    target: "EMULATOR",
    parameters: [
      "VALIDITY_STATUS",
      "TANK-SKIN_TEMP_0",
      "TANK-SKIN_TEMP_1",
      "TANK-SKIN_TEMP_2",
      "RESERVED"
    ],
    commandParams: [],
  },
  {
    id: 85,
    command: "OBC_256_TC_GET_OBC_NVM_REVISION_NUM",
    telemetry: "OBC_256_TM_GET_OBC_NVM_REVISION_NUM",
    target: "EMULATOR",
    parameters: ["SatOS_Arch_Version", "SatOS_Major_Version", "SatOS_Minor_Version", "SatOS_Patch_Version", "NVM_Minor_Version", "NVM_Major_Version", "NVM_Load_Status"],
    commandParams: [],
  },
  {
    id: 86,
    command: "OBC_638_TC_GET_MCU_RST_INFO",
    telemetry: "OBC_638_TM_GET_MCU_RST_INFO",
    target: "EMULATOR",
    parameters: [
      "RESET_REASON_1",
      "EPOCH_TIME_1",
      "RESET_REASON_2",
      "EPOCH_TIME_2",
      "RESET_REASON_3",
      "EPOCH_TIME_3",
      "RESET_REASON_4",
      "EPOCH_TIME_4",
      "RESET_REASON_5",
      "EPOCH_TIME_5",
      "RESET_REASON_6",
      "EPOCH_TIME_6",
      "RESET_REASON_7",
      "EPOCH_TIME_7",
      "RESET_REASON_8",
      "EPOCH_TIME_8",
      "RESET_REASON_9",
      "EPOCH_TIME_9",
      "RESET_REASON_10",
      "EPOCH_TIME_10",
      "RESET_REASON_11",
      "EPOCH_TIME_11",
      "RESET_REASON_12",
      "EPOCH_TIME_12",
      "RESET_REASON_13",
      "EPOCH_TIME_13",
      "RESET_REASON_14",
      "EPOCH_TIME_14",
      "RESET_REASON_15",
      "EPOCH_TIME_15",
      "RESET_REASON_16",
      "EPOCH_TIME_16",
      "RESET_REASON_17",
      "EPOCH_TIME_17",
      "RESET_REASON_18",
      "EPOCH_TIME_18",
      "RESET_REASON_19",
      "EPOCH_TIME_19",
      "RESET_REASON_20",
      "EPOCH_TIME_20",
      "RESET_COUNT",
      "ARRAY_INDEX"
    ],
    commandParams: [],
  },
  {
    id: 87,
    command: "OBC_598_TC_CONFIG_OBC_SELF_RST_TMR",
    telemetry: "OBC_598_TM_CONFIG_OBC_SELF_RST_TMR",
    target: "EMULATOR",
    parameters: ["RESPONSE"],
    commandParams: ["TIMER_CONFIGURATION_VALUE_IN_DAYS"],
  },
  {
    id: 88,
    command: "OBC_599_TC_PS_ES_CONFIG_KEEP_ALIVE_RCVRY_TMOUT",
    telemetry: "OBC_599_TM_PS_ES_CONFIG_KEEP_ALIVE_RCVRY_TMOUT",
    target: "EMULATOR",
    parameters: ["MODULE_ID", "RESPONSE_STATUS"],
    commandParams: ["MODULE_ID", "TIMER_CONFIGURATION_VALUE_IN_SECONDS"],
  },
  {
    id: 89,
    command: "OBC_605_TC_GET_PS_ES_ACTIVE_INTF",
    telemetry: "OBC_605_TM_GET_PS_ES_ACTIVE_INTF",
    target: "EMULATOR",
    parameters: ["MODULE_ID", "ACTIVE_INTERFACE"],
    commandParams: ["INTERFACE_ID"],
  },
  {
    id: 90,
    command: "OBC_604_TC_GET_HINGE_STATUS",
    telemetry: "OBC_604_TM_GET_HINGE_STATUS",
    target: "EMULATOR",
    parameters: [
      "STATUS",
      "HINGE_QUERY_STATUS",
      "HINGE_STATUS_1",
      "HINGE_STATUS_2",
      "HINGE_STATUS_3",
      "HINGE_STATUS_4",
      "HINGE_STATUS_5",
      "HINGE_STATUS_6",
      "HINGE_STATUS_7",
      "HINGE_STATUS_8"
    ],
    commandParams: [],
  },
  {
    id: 91,
    command: "OBC_640_TC_CONFIG_HINGE_RLS_TIMEOUT_TMR",
    telemetry: "OBC_640_TM_CONFIG_HINGE_RLS_TIMEOUT_TMR",
    target: "EMULATOR",
    parameters: ["STATUS"],
    commandParams: ["CONFIGURED_TIMEOUT_VALUE_IN_SECONDS"],
  },
  {
    id: 92,
    command: "OBC_650_TC_SET_XBAND_ROUT_PATH",
    telemetry: "OBC_650_TM_SET_XBAND_ROUT_PATH",
    target: "EMULATOR",
    parameters: ["STATUS"],
    commandParams: ["XBAND_IPCC_PATH"],
  },
  {
    id: 93,
    command: "OBC_503_TC_OBC_MEM_DOWNLOAD",
    telemetry: "OBC_503_TM_OBC_MEM_DOWNLOAD",
    target: "EMULATOR",
    parameters: ["MEMORY_DOWNLOAD_STATUS"],
    commandParams: ["MEMORY_ADDRESS", "MEMORY_SIZE", "FTDS_DELAY", "MTU", "ACK_UNACK", "MEMORY_TYPE", "ACTIVITY_CHECK_WINDOW",],
  },
  {
    id: 94,
    command: "OBC_925_TC_GET_ON_BRD_TEMP",
    telemetry: "OBC_925_TM_GET_ON_BRD_TEMP",
    target: "EMULATOR",
    parameters: [
      "SENSOR_ID",
      "TEMPERATURE_OF_SENSOR_1",
      "EPOCH_TIME_IN_SECONDS_1",
      "TEMPERATURE_OF_SENSOR_2",
      "EPOCH_TIME_IN_SECONDS_2",
      "TEMPERATURE_OF_SENSOR_3",
      "EPOCH_TIME_IN_SECONDS_3",
      "TEMPERATURE_OF_SENSOR_4",
      "EPOCH_TIME_IN_SECONDS_4",
      "TEMPERATURE_OF_SENSOR_5",
      "EPOCH_TIME_IN_SECONDS_5"
    ],
    commandParams: ["SENSOR_ID"],
  },
  {
    id: 95,
    command: "OBC_926_TC_GET_ON_BRD_PWR_INFO",
    telemetry: "OBC_926_TM_GET_ON_BRD_PWR_INFO",
    target: "EMULATOR",
    parameters: [
      "SENSOR_ID",
      "BUS_VOLTAGE_1",
      "SHUNT_VOLTAGE_1",
      "CURRENT_1",
      "POWER_1",
      "EPOCH_TIME_1",
      "BUS_VOLTAGE_2",
      "SHUNT_VOLTAGE_2",
      "CURRENT_2",
      "POWER_2",
      "EPOCH_TIME_2",
      "BUS_VOLTAGE_3",
      "SHUNT_VOLTAGE_3",
      "CURRENT_3",
      "POWER_3",
      "EPOCH_TIME_3",
      "BUS_VOLTAGE_4",
      "SHUNT_VOLTAGE_4",
      "CURRENT_4",
      "POWER_4",
      "EPOCH_TIME_4",
      "BUS_VOLTAGE_5",
      "SHUNT_VOLTAGE_5",
      "CURRENT_5",
      "POWER_5",
      "EPOCH_TIME_5"
    ],
    commandParams: ["SENSOR_ID"],
  },
  {
    id: 96,
    command: "COMMS_334_TC_COMMS_SBAND_BEACON_START",
    telemetry: "COMMS_334_TM_COMMS_SBAND_BEACON_START",
    target: "EMULATOR",
    parameters: ["Status"],
    commandParams: ["RESERVED"],
  },
  {
    id: 97,
    command: "COMMS_335_TC_COMMS_SBAND_BEACON_STOP",
    telemetry: "COMMS_335_TM_COMMS_SBAND_BEACON_STOP",
    target: "EMULATOR",
    parameters: ["Status"],
    commandParams: ["RESERVED"],
  },
  {
    id: 98,
    command: "COMMS_800_TC_UHF_GET_TM_INFO",
    telemetry: "COMMS_800_TM_UHF_GET_TM_INFO",
    target: "EMULATOR",
    parameters: [
      "uptime_in_seconds",
      "Reserved",
      "uart1_rx_count",
      "Reserved",
      "Reserved",
      "Reserved",
      "Reserved",
      "Reserved",
      "Reserved",
      "Pkt_sent",
      "Reserved",
      "Pkt_good",
      "Pkt_rejected_checksum",
      "Reserved",
      "Reserved",
      "Reserved",
      "data_tx_cnt",
      "data_rx_cnt"
    ],
    commandParams: [],
  },
  {
    id: 99,
    command: "COMMS_803_TC_UHF_GET_TX_CFG",
    telemetry: "COMMS_803_TM_UHF_GET_TX_CFG",
    target: "EMULATOR",
    parameters: [
      "Channel_Number",
      "Modulation_Type",
      "Sync_Mode",
      "Enable_DC_filter",
      "FEC_enable",
      "Preamble_Num",
      "Manchester_Enable",
      "Reserved",
      "Base_Frequency_in_Hz",
      "Reserved",
      "Channel_Spacing_in_Hz",
      "Frequency_Offset_in_Hz",
      "Data_Rate_in_bps",
      "Channel_BW",
      "Frequency_deviation_in_Hz"
    ],
    commandParams: [],
  },
  {
    id: 100,
    command: "COMMS_805_TC_UHF_GET_RX_CFG",
    telemetry: "COMMS_805_TM_UHF_GET_RX_CFG",
    target: "EMULATOR",
    parameters: [
      "Channel_Number",
      "Modulation_Type",
      "Sync_Mode",
      "Enable_DC_filter",
      "FEC_enable",
      "Preamble_Num",
      "Manchester_Enable",
      "RX_Attenuation_in_dB",
      "Base_Frequency_in_Hz",
      "Reserved",
      "Channel_Spacing_in_Hz",
      "Frequency_Offset_in_Hz",
      "Data_Rate_in_bps",
      "Channel_BW",
      "Frequency_deviation_in_Hz",
      "RX_Sync_Time_Out"
    ],
    commandParams: [],
  },
  {
    id: 101,
    command: "COMMS_807_TC_UHF_GET_TX_PKT_CFG",
    telemetry: "COMMS_807_TM_UHF_GET_TX_PKT_CFG",
    target: "EMULATOR",
    parameters: [
      "Demod_Sync_Word",
      "Max_Packet_Length",
      "Whitening_Enable",
      "Reserved",
      "CRC_Enable",
      "Reserved",
      "Reserved"
    ],
    commandParams: [],
  },
  {
    id: 102,
    command: "COMMS_809_TC_UHF_GET_RX_PKT_CFG",
    telemetry: "COMMS_809_TM_UHF_GET_RX_PKT_CFG",
    target: "EMULATOR",
    parameters: [
      "Demod_Sync_Word",
      "Max_Packet_Length",
      "Whitening_Enable",
      "Reserved",
      "CRC_Enable",
      "Reserved",
      "Reserved"
    ],
    commandParams: [],
  },
  {
    id: 103,
    command: "COMMS_811_TC_UHF_GET_RX_PKT_CFG",
    telemetry: "COMMS_811_TM_UHF_GET_RX_PKT_CFG",
    target: "EMULATOR",
    parameters: [
      "Reserved",
      "Reserved",
      "LNA_Sel",
      "Filter_Len",
      "Reserved",
      "RF_Output_Power"
    ],
    commandParams: [],
  },
  {
    id: 104,
    command: "COMMS_813_TC_UHF_BEACON_TX_ST",
    telemetry: "COMMS_813_TM_UHF_BEACON_TX_ST",
    target: "EMULATOR",
    parameters: ["Status"],
    commandParams: ["BEACON_TRANSMISSION_STATUS"],
  },
  {
    id: 105,
    command: "COMMS_814_TC_UHF_BEACON_TX_STOP",
    telemetry: "COMMS_814_TM_UHF_BEACON_TX_STOP",
    target: "EMULATOR",
    parameters: ["Status"],
    commandParams: ["BEACON_TRANSMISSION_STATUS"],
  },
];