export const commandTelemetryEmulator = [
  {
    id: 1,
    command: "THRUSTER_1021_TC_EXOTRAIL_GET_SYS_INFO",
    telemetry: "THRUSTER_1021_TM_EXOTRAIL_GET_SYS_INFO",
    target: "EMULATOR",
    parameters: [
      "SOFTWARE_VERSION",
      "EXOTRIAL_OBC_CURRENT_MODE",
      "ID_SAFE",
      "COMMISSIONING_RESULT",
    ],
  },
  {
    id: 2,
    command: "THRUSTER_1022_TC_EXOTRAIL_GET_HEAT_ACTIVITY",
    telemetry: "THRUSTER_1022_TM_EXOTRAIL_GET_HEAT_ACTIVITY",
    target: "EMULATOR",
    parameters: ["THRUSTER_HEATER_ACTIVITY"],
  },
  {
    id: 3,
    command: "THRUSTER_1023_TC_EXOTRAIL_GET_HK_FLUIDIC_INFO",
    telemetry: "THRUSTER_1023_TM_EXOTRAIL_GET_HK_FLUIDIC_INFO",
    target: "EMULATOR",
    parameters: ["ANODE_PULSE_COUNT", "CATHODE_PULSE_COUNT", "TANK_PRESSURE"],
  },
  {
    id: 4,
    command: "THRUSTER_1024_TC_EXOTRAIL_GET_HK_FLUIDIC_INFO",
    telemetry: "THRUSTER_1024_TM_EXOTRAIL_GET_HK_FLUIDIC_INFO",
    target: "EMULATOR",
    parameters: [
      "PPU_OUTPUT_TEMPERATURE",
      "PPU_INPUT_VOLTAGE",
      "PPU_INPUT_CURRENT",
      "PPU_INPUT_TEMPERATURE",
    ],
  },
  {
    id: 5,
    command: "THRUSTER_1025_TC_EXOTRAIL_GET_HK_THERMIC_INFO",
    telemetry: "THRUSTER_1025_TM_EXOTRAIL_GET_HK_THERMIC_INFO",
    target: "EMULATOR",
    parameters: [
      "TEMPERATURE_OF_THD_SUPPORT_1",
      "TEMPERATURE_OF_THD_RADIATOR_1",
      "TEMPERATURE_OF_THD_RADIATOR_2",
      "TEMPERATURE_OF_TCU_OBC_1",
      "TEMPERATURE_OF_PMS_ANODE_1",
      "TEMPERATURE_OF_PMS_ANODE_2",
      "TEMPERATURE_OF_PMS_CATHODE_1",
      "TEMPERATURE_OF_PMS_CATHODE_2",
      "TEMPERATURE_OF_PMS_INTERFACE_2",
    ],
  },
  {
    id: 6,
    command: "OBC_581_TC_GET_CUR_TIME",
    telemetry: "OBC_581_TM_GET_CUR_TIME",
    target: "EMULATOR",
    parameters: [
      "Status",
      "Year",
      "Month",
      "Date",
      "Hours",
      "Minute",
      "Milliseconds",
    ],
  },
  {
    id: 7,
    command: "THRUSTER_1026_TC_EXOTRAIL_GET_HK_POWER_INFO",
    telemetry: "THRUSTER_1026_TM_EXOTRAIL_GET_HK_POWER_INFO",
    target: "EMULATOR",
    parameters: [
      "Thruster_input_voltage_15v",
      "Thruster_2v5_ref_volt",
      "Thruster_input_volt_5v",
      "Thruster_input_volt_3v3",
    ],
  },
  {
    id: 8,
    command: "THRUSTER_1027_TC_EXOTRAIL_GET_SAFE_LIMIT",
    telemetry: "THRUSTER_1027_TM_EXOTRAIL_GET_HK_FLUIDIC_INFO",
    target: "EMULATOR",
    parameters: [
      "Maximum_temperature_limit_for_Thruster_Head_Radiator_1",
      "Minimum_temperature_limit_for_Thruster_Head_Radiator_1",
      "Maximum_temperature_limit_for_Thruster_PMS_Anode_1",
      "Minimum_temperature_limit_for_Thruster_PMS_Anode_1",
      "Maximum_temperature_limit_for_Thruster_PMS_Cathode_1",
      "Minimum_temperature_limit_for_Thruster_PMS_Cathode_1",
      "Maximum_temperature_limit_for_Thruster_Head_Radiator_2",
      "Minimum_temperature_limit_for_Thruster_Head_Radiator_2",
      "Maximum_temperature_limit_for_Thruster_PMS_Anode_2",
      "Minimum_temperature_limit_for_Thruster_PMS_Anode_2",
      "Maximum_temperature_limit_for_Thruster_PMS_Cathode_2",
      "Minimum_temperature_limit_for_Thruster_PMS_Cathode_2",
      "Maximum_temperature_limit_for_Thruster_PMS_Pressure_1",
      "Minimum_temperature_limit_for_Thruster_PMS_Pressure_1",
      "Maximum_temperature_limit_for_Thruster_Thruster_Head_Supply_1",
      "Minimum_temperature_limit_for_Thruster_Head_Supply_1",
      "Maximum_temperature_limit_for_Thruster_TCU_OnBoard_Computer_1",
      "Minimum_temperature_limit_for_Thruster_TCU_OnBoard_Computer_1",
      "Maximum_temperature_for_PPU",
      "Maximum_pressure_for_tank",
    ],
  },
  {
    id: 9,
    command: "THRUSTER_1028_TC_EXOTRAIL_GET_FLUIDIC_VALVE_SEL",
    telemetry: "THRUSTER_1028_TM_EXOTRAIL_GET_FLUIDIC_VALVE_SEL",
    target: "EMULATOR",
    parameters: ["FLUIDIC_VALVE_MODE"],
  },
  {
    id: 10,
    command: "THRUSTER_1029_TC_EXOTRAIL_GET_HEATER_CFG",
    telemetry: "THRUSTER_1029_TM_EXOTRAIL_GET_HEATER_CFG",
    target: "EMULATOR",
    parameters: [
      "RADIATOR_LOW_TEMPERATURE",
      "RADIATOR_HIGH_TEMPERATURE",
      "RADIATOR_HEATING_DURATIONS_IN_MINUTES",
    ],
  },
  {
    id: 11,
    command: "THRUSTER_1030_TC_EXOTRAIL_SET_FIRING_OPERATING_POINT",
    telemetry: "THRUSTER_1030_TM_EXOTRAIL_SET_FIRING_OPERATING_POINT",
    target: "EMULATOR",
    parameters: ["EXOTRAIL_MODE"],
  },
  {
    id: 12,
    command: "THRUSTER_1031_TC_EXOTRAIL_TEST_SET_OBC_MODE",
    telemetry: "THRUSTER_1031_TM_EXOTRAIL_TEST_SET_OBC_MODE",
    target: "EMULATOR",
    parameters: ["EXOTRIAL_OBC_MODE"],
  },
  {
    id: 13,
    command: "THRUSTER_1033_TC_EXOTRAIL_SET_SAFE_LIMIT",
    telemetry: "THRUSTER_1033_TM_EXOTRAIL_SET_SAFE_LIMIT",
    target: "EMULATOR",
    parameters: ["EXOTRAIL_MODE"],
  },
  {
    id: 14,
    command: "THRUSTER_1034_TC_EXOTRAIL_SET_FLUIDIC_VALVE_SEL",
    telemetry: "THRUSTER_1034_TM_EXOTRAIL_SET_FLUIDIC_VALVE_SEL",
    target: "EMULATOR",
    parameters: ["EXOTRAIL_MODE"],
  },
  {
    id: 15,
    command: "THRUSTER_1036_TC_EXOTRAIL_SET_FIRING_DURATION",
    telemetry: "THRUSTER_1036_TM_EXOTRAIL_SET_FIRING_DURATION",
    target: "EMULATOR",
    parameters: ["EXOTRAIL_MODE"],
  },
  {
    id: 16,
    command: "THRUSTER_1038_TC_OBC_EXOTRIAL_THRUSTER_TM_DECODE_DATA",
    telemetry: "THRUSTER_1038_TM_OBC_EXOTRIAL_THRUSTER_TM_DECODE_DATA",
    target: "EMULATOR",
    parameters: [
      "SOFTWARE_VERSION",
      "CURRENT_MODE_OF_OBC_IN_THRUSTER",
      "SAFETY_IDENTIFIER",
      "HEATER_ACTIVITY_STATUS",
      "PULSE_COUNT_FOR_ANODE_VALUE",
      "PULSE_COUNT_FOR_CATHODE_VALUE",
      "COMMISSIONING_RESULT",
      "PPU_OUTPUT_TEMP",
      "INPUT_VOLTAGE_MEASUREMENT",
      "INPUT_CURRENT_MEASUREMENT",
      "PPU_INPUT_TEMPERATURE",
      "TANK_PRESSURE",
      "TEMPERATURE_OF_THRUSTER_HEAD_SUPPORT_1",
      "TEMPERATURE_OF_THRUSTER_HEAD_RADIATOR_1",
      "TEMPERATURE_OF_THRUSTER_HEAD_RADIATOR_2",
      "TEMPERATURE_OF_TCU_ON_BOARD_CONTROLLER_1",
      "TEMPERATURE_OF_TANK_1_PMS_1",
      "TEMPERATURE_OF_TANK_2_PMS_1",
      "TEMPERATURE_OF_TANK_2_PMS_2",
      "TEMPERATURE_OF_TANK_2_PMS_3",
      "TEMPERATURE_OF_PMS_ANODE_1",
      "TEMPERATURE_OF_PMS_ANODE_2",
      "TEMPERATURE_OF_PMS_CATHODE_1",
      "TEMPERATURE_OF_PMS_CATHODE_2",
      "TEMPERATURE_OF_PMS_PRESSURE_1",
      "TEMPERATURE_OF_TANK_3_1_IN_PMS",
      "TEMPERATURE_OF_TANK_3_2_IN_PMS",
      "VOLTAGE_MEASUREMENT_AT_15V_INPUT",
      "POWER_15V_VALVES_2_AND_4",
      "REFERENCE_VOLTAGE_2V5",
      "VOLTAGE_MEASUREMENT_5V_INPUT",
      "VOLTAGE_MEASUREMENT_3V3_INPUT",
      "THRUSTER_OBC_MODE",
      "THERMAL_MEASUREMENT_FREQUENCY",
      "DURATION_OF_FIRING_EVENT",
      "LOWER_SETPOINT_RADIATOR_TEMP",
      "UPPER_SETPOINT_RADIATOR_TEMP",
      "RADIATOR_HEATING_DURATION",
      "LOWER_SETPOINT_TANK1",
      "UPPER_SETPOINT_TANK1",
      "TANK1_HEATING_DURATION",
      "LOWER_SETPOINT_TANK2",
      "UPPER_SETPOINT_TANK2",
      "TANK2_HEATING_DURATION",
      "LOWER_SETPOINT_TANK3",
      "UPPER_SETPOINT_TANK3",
      "TANK3_HEATING_DURATION",
      "FLUIDIC_VALVE_SELECTION",
      "MAX_THR_HEAD_RAD1_THERM_LIMIT",
      "MIN_THR_HEAD_RAD1_THERM_LIMIT",
      "MAX_PMS_ANODE1_THERM_LIMIT",
      "MIN_PMS_ANODE1_THERM_LIMIT",
      "MAX_PMS_CATHODE1_THERM_LIMIT",
      "MIN_PMS_CATHODE1_THERM_LIMIT",
      "MAX_THR_HEAD_RAD2_THERM_LIMIT",
      "MIN_THR_HEAD_RAD2_THERM_LIMIT",
      "MAX_PMS_ANODE2_THERM_LIMIT",
      "MIN_PMS_ANODE2_THERM_LIMIT",
      "MAX_PMS_CATHODE2_THERM_LIMIT",
      "MIN_PMS_CATHODE2_THERM_LIMIT",
      "MAX_PMS_PRESSURE1_THERM_LIMIT",
      "MIN_PMS_PRESSURE1_THERM_LIMIT",
      "MAX_THR_HEAD_SUPERVISION1_LIMIT",
      "MIN_THR_HEAD_SUPERVISION1_LIMIT",
      "MAX_TCU_OBC1_LIMIT",
      "MIN_TCU_OBC1_LIMIT",
      "MAX_PPU_TEMP_LIMIT",
      "MAX_TANK_PRESSURE",
      "MAGIC_NUMBER_1",
      "MAGIC_NUMBER_2",
      "STRUCTURE_END_FLAG_1",
      "STRUCTURE_END_FLAG_2",
    ],
  },
  {
    id: 17,
    command: "OBC_500_TC_GET_PROC_UTIL_INFO",
    telemetry: "OBC_500_TM_GET_PROC_UTIL_INFO",
    target: "EMULATOR",
    parameters: ["CPU_USAGE"],
  },
  {
    id: 18,
    command: "OBC_550_TC_SET_CUR_TIME",
    telemetry: "OBC_550_TM_SET_CUR_TIME",
    target: "EMULATOR",
    parameters: [
      "Year",
      "Month",
      "Date",
      "Hours",
      "Minute",
      "Milliseconds",
      "Status",
    ],
  },
  {
    id: 19,
    command: "FTM_SEND_DATA_PCKTS",
    telemetry: "",
    target: "EMULATOR",
    parameters: [],
  },
  {
    id: 20,
    command: "TC_547",
    telemetry: "TM_547",
    target: "EMULATOR",
    parameters: ["SEGMENT_ID", "LUT_ID"],
  },
  {
    id: 21,
    command: "TC_549",
    telemetry: "549_TM",
    target: "EMULATOR",
    parameters: [
      "Response_type",
      "UL_STATUS_1",
      "TOTAL_SEGMENTS_IN_LUT_1",
      "TOTAL_EVENTS_IN_LUT_1",
      "CURRENT_SEGMENT_ID",
      "CURRENT_EVENT_COUNT",
      "ID_OF_SEGMENTS_EXPECTED",
      "ID_OF_SEGMENTS_EXPECTED_7",
      "ID_OF_SEGMENTS_EXPECTED_6",
      "ID_OF_SEGMENTS_EXPECTED_5",
      "ID_OF_SEGMENTS_EXPECTED_4",
      "ID_OF_SEGMENTS_EXPECTED_3",
      "ID_OF_SEGMENTS_EXPECTED_2",
      "ID_OF_SEGMENTS_EXPECTED_1",
      "ID_OF_SEGMENTS_EXPECTED_0",
      "ID_OF_SEGMENTS_RECEIVED",
      "ID_OF_SEGMENTS_RECEIVED_7",
      "ID_OF_SEGMENTS_RECEIVED_6",
      "ID_OF_SEGMENTS_RECEIVED_5",
      "ID_OF_SEGMENTS_RECEIVED_4",
      "ID_OF_SEGMENTS_RECEIVED_3",
      "ID_OF_SEGMENTS_RECEIVED_2",
      "ID_OF_SEGMENTS_RECEIVED_1",
      "ID_OF_SEGMENTS_RECEIVED_0",
      "ID_OF_SEGMENTS_EXECUTED",
      "ID_OF_SEGMENTS_EXECUTED_7",
      "ID_OF_SEGMENTS_EXECUTED_6",
      "ID_OF_SEGMENTS_EXECUTED_5",
      "ID_OF_SEGMENTS_EXECUTED_4",
      "ID_OF_SEGMENTS_EXECUTED_3",
      "ID_OF_SEGMENTS_EXECUTED_2",
      "ID_OF_SEGMENTS_EXECUTED_1",
      "ID_OF_SEGMENTS_EXECUTED_0",
      "RESERVED_1",
    ],
  },
  {
    id: 22,
    command: "TC_CONOPS_LUT_RUN_CTRL",
    telemetry: "TM_CONOPS_SCH_LUT_RUN_CTRL",
    target: "EMULATOR",
    parameters: ["STATUS"],
  },
  {
    id: 23,
    command: "TC_DEFFERED_STRG_OPT",
    telemetry: "TM_DEFERRED_STORAGE",
    target: "EMULATOR",
    parameters: ["ADDRESS_OFFSET"],
  },
  {
    id: 24,
    command: "ADCS_129_TC_GET_ADCS_STATE_INFO",
    telemetry: "ADCS_129_TM_GET_ADCS_STATE_INFO",
    target: "EMULATOR",
    parameters: [
      "SOF3",
      "SOF4",
      "ID",
      "STATUS",
      "ATTITUDE_ESTIMATION_MODE",
      "CONTROL_MODE",
      "RESERVED",
      "EOF1",
      "EOF2",
    ],
  },
  {
    id: 25,
    command: "ADCS_19_TC_3_AXIS_STABALISATION_MODE",
    telemetry: "ADCS_19_TM_SET_ADCS_CTRL_MODE_CONF",
    target: "EMULATOR",
    parameters: ["SOF3", "SOF4", "ID", "STATUS", "EOF1", "EOF2"],
  },
  {
    id: 26,
    command: "ADCS_133_TC_GET_ADCS_MAG_FIELD_VEC",
    telemetry: "ADCS_133_TM_GET_ADCS_MAG_FIELD_VEC",
    target: "EMULATOR",
    parameters: [
      "SOF3",
      "SOF4",
      "ID",
      "STATUS",
      "X_AXIS_MAGNETIC_FIELD_VECTOR",
      "Y_AXIS_MAGNETIC_FIELD_VECTOR",
      "Z_AXIS_MAGNETIC_FIELD_VECTOR",
      "EOF1",
      "EOF2",
    ],
  },
  {
    id: 27,
    command: "ADCS_117_TC_GET_ADCS_SAT_VEL_ECEF",
    telemetry: "ADCS_117_TM_GET_ADCS_SAT_VEL_ECEF",
    target: "EMULATOR",
    parameters: [
      "SOF3",
      "SOF4",
      "ID",
      "STATUS",
      "ECEF_REFERENCED_X_VELOCITY",
      "ECEF_REFERENCED_Y_VELOCITY",
      "ECEF_REFERENCED_Z_VELOCITY",
      "EOF1",
      "EOF2",
    ],
  },
  {
    id: 28,
    command: "ADCS_134_TC_GET_ADCS_CSS_VEC",
    telemetry: "ADCS_134_TM_GET_ADCS_CSS_VEC",
    target: "EMULATOR",
    parameters: [
      "SOF3",
      "SOF4",
      "ID",
      "STATUS",
      "X_AXIS_SUN_VECTOR",
      "Y_AXIS_SUN_VECTOR",
      "Z_AXIS_SUN_VECTOR",
      "EOF1",
      "EOF2",
    ],
  },
  {
    id: 29,
    command: "ADCS_137_TC_GET_ADCS_MEAS_RATE",
    telemetry: "ADCS_137_TM_GET_ADCS_MEAS_RATE",
    target: "EMULATOR",
    parameters: [
      "SOF3",
      "SOF4",
      "ID",
      "STATUS",
      "Measured_X_Angular_Rate",
      "Measured_Y_Angular_Rate",
      "Measured_Z_Angular_Rate",
      "EOF1",
      "EOF2",
    ],
  },
  {
    id: 30,
    command: "ADCS_184_TC_GET_ADCS_EST_RATE",
    telemetry: "ADCS_184_TM_GET_ADCS_EST_RATE",
    target: "EMULATOR",
    parameters: [
      "SOF3",
      "SOF4",
      "ID",
      "STATUS",
      "Estimated_X_Angular_Rate",
      "Estimated_Y_Angular_Rate",
      "Estimated_Z_Angular_Rate",
      "EOF1",
      "EOF2",
    ],
  },
  {
    id: 31,
    command: "ADCS_241_TC_GET_ADCS_EST_ATTITUDE",
    telemetry: "ADCS_241_TM_GET_ADCS_EST_ATTITUDE",
    target: "EMULATOR",
    parameters: [
      "SOF3",
      "SOF4",
      "ID",
      "STATUS",
      "Estimated_Quaternion_1_wrt_ECI",
      "Estimated_Quaternion_2_wrt_ECI",
      "Estimated_Quaternion_3_wrt_ECI",
      "Estimated_Quaternion_4_wrt_ECI",
      "EOF1",
      "EOF2",
    ],
  },
  {
    id: 32,
    command: "ADCS_177_TC_GET_ADCS_CMD_ATTITUDE",
    telemetry: "ADCS_177_TM_GET_ADCS_CMD_ATTITUDE",
    target: "EMULATOR",
    parameters: [
      "SOF3",
      "SOF4",
      "ID",
      "STATUS",
      "Command_Quaternion_1_wrt_ECI",
      "Command_Quaternion_2_wrt_ECI",
      "Command_Quaternion_3_wrt_ECI",
      "Command_Quaternion_4_wrt_ECI",
      "EOF1",
      "EOF2",
    ],
  },
  {
    id: 33,
    command: "ADCS_253_TC_ADCS_STATE_CFG",
    telemetry: "ADCS_253_TM_ADCS_STATE_CFG",
    target: "EMULATOR",
    parameters: [
      "SOF3",
      "SOF4",
      "ID",
      "STATUS",
      "Auto_commissioning_flag",
      "RESERVED",
      "EOF1",
      "EOF2",
    ],
  },
  {
    id: 34,
    command: "ADCS_195_TC_GET_ADCS_RW_SPEED_DATA",
    telemetry: "ADCS_195_TM_GET_ADCS_RW_SPEED_DATA",
    target: "EMULATOR",
    parameters: [
      "SOF3",
      "SOF4",
      "ID",
      "STATUS",
      "Reaction_wheel_instance_ID",
      "Command_Wheel_Speed_1",
      "Command_Wheel_Speed_2",
      "Command_Wheel_Speed_3",
      "Command_Wheel_Speed_4",
      "EOF1",
      "EOF2",
    ],
  },
  {
    id: 35,
    command: "ADCS_196_TC_GET_ADCS_RW_SPEED_MEASURE",
    telemetry: "ADCS_196_TM_GET_ADCS_RW_SPEED_MEASURE",
    target: "EMULATOR",
    parameters: [
      "SOF3",
      "SOF4",
      "ID",
      "STATUS",
      "Reaction_wheel_instance_ID",
      "Measured_Wheel_Speed_1",
      "Measured_Wheel_Speed_2",
      "Measured_Wheel_Speed_3",
      "Measured_Wheel_Speed_4",
      "EOF1",
      "EOF2",
    ],
  },
  {
    id: 36,
    command: "ADCS_142_TC_GET_ADCS_RW_MAGMTR",
    telemetry: "ADCS_142_TM_GET_ADCS_RW_MAGMTR",
    target: "EMULATOR",
    parameters: [
      "SOF3",
      "SOF4",
      "ID",
      "STATUS",
      "Reaction_wheel_instance_ID",
      "Raw_Magnetometer_X_Measurement",
      "Raw_Magnetometer_Y_Measurement",
      "Raw_Magnetometer_Z_Measurement",
      "EOF1",
      "EOF2",
    ],
  },
  {
    id: 37,
    command: "ADCS_248_TC_GET_ADCS_RAW_CSS",
    telemetry: "ADCS_248_TM_GET_ADCS_RAW_CSS",
    target: "EMULATOR",
    parameters: [
      "SOF3",
      "SOF4",
      "ID",
      "STATUS",
      "CSS_ID",
      "CSS_AD_value_1",
      "CSS_AD_value_2",
      "CSS_AD_value_3",
      "CSS_AD_value_4",
      "CSS_AD_value_5",
      "CSS_AD_value_6",
      "CSS_AD_value_7",
      "CSS_AD_value_8",
      "CSS_AD_value_9",
      "CSS_AD_value_10",
      "CSS_AD_value_11",
      "CSS_AD_value_12",
      "EOF1",
      "EOF2",
    ],
  },
  {
    id: 38,
    command: "ADCS_187_TC_GET_ADCS_MODL_MAG_VEC_DATA",
    telemetry: "ADCS_187_TM_GET_ADCS_MODL_MAG_VEC_DATA",
    target: "EMULATOR",
    parameters: [
      "SOF3",
      "SOF4",
      "ID",
      "STATUS",
      "X_AXIS_MAGNETIC_FIELD_VECTOR",
      "Y_AXIS_MAGNETIC_FIELD_VECTOR",
      "Z_AXIS_MAGNETIC_FIELD_VECTOR",
      "EOF1",
      "EOF2",
    ],
  },
  {
    id: 39,
    command: "ADCS_188_TC_GET_ADCS_MODL_SUN_VEC_DATA",
    telemetry: "ADCS_188_TM_GET_ADCS_MODL_SUN_VEC_DATA",
    target: "EMULATOR",
    parameters: [
      "SOF3",
      "SOF4",
      "ID",
      "STATUS",
      "X_AXIS_SUN_VECTOR",
      "Y_AXIS_SUN_VECTOR",
      "Z_AXIS_SUN_VECTOR",
      "EOF1",
      "EOF2",
    ],
  },
  {
    id: 40,
    command: "ADCS_181_TC_GET_ADCS_SAT_POS_ECI",
    telemetry: "ADCS_181_TM_GET_ADCS_SAT_POS_ECI",
    target: "EMULATOR",
    parameters: [
      "SOF3",
      "SOF4",
      "ID",
      "STATUS",
      "ECI_Referenced_X_Coordinate",
      "ECI_Referenced_Y_Coordinate",
      "ECI_Referenced_Z_Coordinate",
      "EOF1",
      "EOF2",
    ],
  },
  {
    id: 41,
    command: "ADCS_182_TC_GET_ADCS_SAT_VELOCITY_DATA",
    telemetry: "ADCS_182_TM_GET_ADCS_SAT_VELOCITY_DATA",
    target: "EMULATOR",
    parameters: [
      "SOF3",
      "SOF4",
      "ID",
      "STATUS",
      "ECI_Referenced_X_Velocity",
      "ECI_Referenced_Y_Velocity",
      "ECI_Referenced_Z_Velocity",
      "EOF1",
      "EOF2",
    ],
  },
  {
    id: 42,
    command: "ADCS_111_TC_GET_ADCS_ERR_VALID_METRICS",
    telemetry: "ADCS_111_TM_GET_ADCS_ERR_VALID_METRICS",
    target: "EMULATOR",
    parameters: [
      "SOF3",
      "SOF4",
      "ID",
      "STATUS",
      "GOOD_ATTITUDE_TIMER",
      "EIGEN_ERROR",
      "Safe_mode_Sun_Pointing_State",
      "ATTITUDE_VALIDITY",
      "REFERENCE_VALIDITY",
      ,
      "TIME_VALIDITY",
      "NUMBER_OF_TRACKER",
      "TRACKER_ATTITUDE_STATUS_1",
      "TRACKER_ATTITUDE_STATUS_2",
      "EOF1",
      "EOF2",
    ],
  },
  {
    id: 43,
    command: "ADCS_19_TC_FINE_SUN_POINTING",
    telemetry: "ADCS_19_TM_SET_ADCS_CTRL_MODE_CONF",
    target: "EMULATOR",
    parameters: ["SOF3", "SOF4", "ID", "STATUS", "EOF1", "EOF2"],
  },
  {
    id: 44,
    command: "ADCS_19_TC_SUN_POINTING_CONTROL_MODE",
    telemetry: "ADCS_19_TM_SET_ADCS_CTRL_MODE_CONF",
    target: "EMULATOR",
    parameters: ["SOF3", "SOF4", "ID", "STATUS", "EOF1", "EOF2"],
  },
  {
    id: 45,
    command: "ADCS_19_TC_NADIR_POINTING",
    telemetry: "ADCS_19_TM_SET_ADCS_CTRL_MODE_CONF",
    target: "EMULATOR",
    parameters: ["SOF3", "SOF4", "ID", "STATUS", "EOF1", "EOF2"],
  },
  {
    id: 46,
    command: "ADCS_19_TC_TARGET_TRACKING_CONTROL_MODE_ECEF_TARGET_REFERENCE",
    telemetry: "ADCS_19_TM_SET_ADCS_CTRL_MODE_CONF",
    target: "EMULATOR",
    parameters: ["SOF3", "SOF4", "ID", "STATUS", "EOF1", "EOF2"],
  },
  {
    id: 47,
    command: "ADCS_19_TC_TARGET_TRACKING_CONTROL_MODE_WITH_ADDITIONAL_CONTROL",
    telemetry: "ADCS_19_TM_SET_ADCS_CTRL_MODE_CONF",
    target: "EMULATOR",
    parameters: ["SOF3", "SOF4", "ID", "STATUS", "EOF1", "EOF2"],
  },
  {
    id: 48,
    command: "OBC_610_TC_GET_TEMP",
    telemetry: "OBC_610_TM_GET_TEMP",
    target: "EMULATOR",
    parameters: ["DEVICE_ID", "TEMPERATURE"],
  },
  {
    id: 49,
    command: "OBC_611_TC_GET_TIME",
    telemetry: "OBC_611_TM_GET_TIME",
    target: "EMULATOR",
    parameters: ["DEVICE_ID", "MCU_UPTIME", "EPOCH_TIME"],
  },

  {
    id: 50,
    command: "OBC_545_TC_PLD_VM_PWR_ON",
    telemetry: "OBC_545_TM_PLD_VM_PWR_ON",
    target: "EMULATOR",
    parameters: ["STATUS"],
  },
  {
    id: 51,
    command: "OBC_546_TC_PLD_VM_PWR_OFF",
    telemetry: "OBC_546_TM_PLD_VM_PWR_OFF",
    target: "EMULATOR",
    parameters: ["STATUS"],
  },
  {
    id: 52,
    command: "OBC_508_TC_CONFIG_AUTO_LEOP_TRIGGER_TMR",
    telemetry: "OBC_508_TM_CONFIG_AUTO_LEOP_TRIGGER_TMR",
    target: "EMULATOR",
    parameters: ["Response_Status"],
  },
  {
    id: 53,
    command: "OBC_508_TC_TRIGGER_HINGE_PROCESS",
    telemetry: "OBC_508_TM_TRIGGER_HINGE_PROCESS",
    target: "EMULATOR",
    parameters: ["Response"],
  },
  {
    id: 54,
    command: "OBC_505_TC_GET_AUTO_LEOPS_STATE",
    telemetry: "OBC_505_TC_GET_AUTO_LEOPS_STATE",
    target: "EMULATOR",
    parameters: ["Satellite_Body_Axis_1"],
  },
  {
    id: 55,
    command: "OBC_602_TC_TRIGGER_HINGE_PROCESS",
    telemetry: "OBC_602_TM_TRIGGER_HINGE_PROCESS",
    target: "EMULATOR",
    parameters: ["Response"],
  },
];
